# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-22076-Inspiron-5547/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl
    /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog
  } {
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv
    }
      rt::read_verilog -include {
    /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl
    /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog
  } {
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_b_atc.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_w_atc.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_atc.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/processing_system7_v5_5/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ip/xc7z020_processing_system7_0_1/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ip/xc7z020_processing_system7_0_1/synth/xc7z020_processing_system7_0_1.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_and.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_or.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_si_transactor.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_splitter.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_router.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ip/xc7z020_xbar_0/synth/xc7z020_xbar_0.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ip/xc7z020_auto_pc_0/synth/xc7z020_auto_pc_0.v
    }
      rt::read_vhdl -lib axi_bram_ctrl_v4_0_8 {
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/srl_fifo.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/axi_bram_ctrl_funcs.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/coregen_comp_defs.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/axi_lite_if.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/checkbit_handler_64.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/checkbit_handler.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/correct_one_bit_64.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/correct_one_bit.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/xor18.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/parity.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/ecc_gen.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/lite_ecc_reg.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/axi_lite.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/sng_port_arb.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/ua_narrow.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/wrap_brst.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/rd_chnl.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/wr_chnl.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/full_axi.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/axi_bram_ctrl_top.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/axi_bram_ctrl_v4_0/hdl/vhdl/axi_bram_ctrl.vhd
    }
      rt::read_vhdl -lib blk_mem_gen_v8_3_3 {
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/blk_mem_gen_v8_3/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/blk_mem_gen_v8_3/hdl/blk_mem_gen_v8_3.vhd
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ip/xc7z020_axi_bram_ctrl_0_0/synth/xc7z020_axi_bram_ctrl_0_0.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ip/xc7z020_rst_processing_system7_0_100M_0/synth/xc7z020_rst_processing_system7_0_100M_0.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ip/xc7z020_axi_bram_ctrl_0_bram_0/synth/xc7z020_axi_bram_ctrl_0_bram_0.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/hdl/xc7z020.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/hdl/xc7z020_wrapper.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/new/top.vhd
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/lib_cdc_v1_0/hdl/src/vhdl/cdc_sync.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_9 {
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/upcnt_n.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/sequence_psr.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/lpf.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/proc_sys_reset.vhd
    }
      rt::read_vhdl -lib fifo_generator_v13_1_1 {
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/fifo_generator_v13_1/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      /home/jlim/Documents/school/DLA/source/fw/rsa2048/rsa2048.srcs/sources_1/bd/xc7z020/ipshared/xilinx.com/fifo_generator_v13_1/hdl/fifo_generator_v13_1.vhd
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-22076-Inspiron-5547/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
