webtalk_init -webtalk_dir /home/linux/Documents/DLA/source/fw/rsa2048/rsa2048.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 12 17:57:43 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "73v7qc4gjiiiu3ba3jdupq9vbn" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1484267389000" -context "sdk\\\\hardware/1484267389000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1484267389000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1484267389000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1484267389000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1484267389000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1484267389000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1484267389000"
webtalk_add_data -client sdk -key uid -value "1484267464000" -context "sdk\\\\bsp/1484267464000"
webtalk_add_data -client sdk -key hwid -value "1484267389000" -context "sdk\\\\bsp/1484267464000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1484267464000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1484267464000"
webtalk_add_data -client sdk -key uid -value "1484267488000" -context "sdk\\\\application/1484267488000"
webtalk_add_data -client sdk -key hwid -value "1484267389000" -context "sdk\\\\application/1484267488000"
webtalk_add_data -client sdk -key bspid -value "1484267464000" -context "sdk\\\\application/1484267488000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1484267488000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1484267488000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1484267488000"
webtalk_add_data -client sdk -key uid -value "1484267533000" -context "sdk\\\\bsp/1484267533000"
webtalk_add_data -client sdk -key hwid -value "1484267389000" -context "sdk\\\\bsp/1484267533000"
webtalk_add_data -client sdk -key os -value "device_tree" -context "sdk\\\\bsp/1484267533000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1484267533000"
webtalk_transmit -clientid 3925594485 -regid "" -xml /home/linux/Documents/DLA/source/fw/rsa2048/rsa2048.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/linux/Documents/DLA/source/fw/rsa2048/rsa2048.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/linux/Documents/DLA/source/fw/rsa2048/rsa2048.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
