#pragma line 1 "BigInt/solution1/bigint/BigIntegerAlgorithms.cc" ::: 0
#pragma line 1 "BigInt/solution1/bigint/BigIntegerAlgorithms.cc" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 145 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 407 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 198
#pragma line 421 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 201
#pragma line 6 "<command line>" 2 ::: 203
#pragma line 1 "<built-in>" 2 ::: 204
#pragma line 1 "BigInt/solution1/bigint/BigIntegerAlgorithms.cc" 2 ::: 205
#pragma line 1 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigIntegerAlgorithms.hh" 1 ::: 206
#pragma line 1 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigInteger.hh" 1 ::: 210
#pragma line 1 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigUnsigned.hh" 1 ::: 214
#pragma line 1 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./NumberlikeArray.hh" 1 ::: 218
#pragma line 5 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigUnsigned.hh" 2 ::: 394
#pragma line 5 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigInteger.hh" 2 ::: 807
#pragma line 5 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigIntegerAlgorithms.hh" 2 ::: 1017
#pragma line 2 "BigInt/solution1/bigint/BigIntegerAlgorithms.cc" 2 ::: 1037
