#pragma line 1 "BigInt/solution1/bigint/BigInteger.cc" ::: -10
#pragma line 1 "BigInt/solution1/bigint/BigInteger.cc" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 145 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 407 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 188
#pragma line 421 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 191
#pragma line 6 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "BigInt/solution1/bigint/BigInteger.cc" 2 ::: 195
#pragma line 1 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigInteger.hh" 1 ::: 196
#pragma line 1 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigUnsigned.hh" 1 ::: 200
#pragma line 1 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./NumberlikeArray.hh" 1 ::: 204
#pragma line 5 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigUnsigned.hh" 2 ::: 380
#pragma line 5 "/home/linux/Documents/DLA/source/sw/BigInt/solution1/bigint/./BigInteger.hh" 2 ::: 793
#pragma line 2 "BigInt/solution1/bigint/BigInteger.cc" 2 ::: 1003
#pragma line 172 "BigInt/solution1/bigint/BigInteger.cc" ::: 1166
