// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

`timescale 1ns/1ps
module encrypt_PERIPH_BUS_s_axi
#(parameter
    C_S_AXI_ADDR_WIDTH = 8,
    C_S_AXI_DATA_WIDTH = 32
)(
    // axi4 lite slave signals
    input  wire                          ACLK,
    input  wire                          ARESET,
    input  wire                          ACLK_EN,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] AWADDR,
    input  wire                          AWVALID,
    output wire                          AWREADY,
    input  wire [C_S_AXI_DATA_WIDTH-1:0] WDATA,
    input  wire [C_S_AXI_DATA_WIDTH/8-1:0] WSTRB,
    input  wire                          WVALID,
    output wire                          WREADY,
    output wire [1:0]                    BRESP,
    output wire                          BVALID,
    input  wire                          BREADY,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] ARADDR,
    input  wire                          ARVALID,
    output wire                          ARREADY,
    output wire [C_S_AXI_DATA_WIDTH-1:0] RDATA,
    output wire [1:0]                    RRESP,
    output wire                          RVALID,
    input  wire                          RREADY,
    output wire                          interrupt,
    // user signals
    output wire                          ap_start,
    input  wire                          ap_done,
    input  wire                          ap_ready,
    input  wire                          ap_idle,
    output wire [511:0]                  key_V,
    input  wire [511:0]                  output_V,
    input  wire                          output_V_ap_vld
);
//------------------------Address Info-------------------
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of key_V
//        bit 31~0 - key_V[31:0] (Read/Write)
// 0x14 : Data signal of key_V
//        bit 31~0 - key_V[63:32] (Read/Write)
// 0x18 : Data signal of key_V
//        bit 31~0 - key_V[95:64] (Read/Write)
// 0x1c : Data signal of key_V
//        bit 31~0 - key_V[127:96] (Read/Write)
// 0x20 : Data signal of key_V
//        bit 31~0 - key_V[159:128] (Read/Write)
// 0x24 : Data signal of key_V
//        bit 31~0 - key_V[191:160] (Read/Write)
// 0x28 : Data signal of key_V
//        bit 31~0 - key_V[223:192] (Read/Write)
// 0x2c : Data signal of key_V
//        bit 31~0 - key_V[255:224] (Read/Write)
// 0x30 : Data signal of key_V
//        bit 31~0 - key_V[287:256] (Read/Write)
// 0x34 : Data signal of key_V
//        bit 31~0 - key_V[319:288] (Read/Write)
// 0x38 : Data signal of key_V
//        bit 31~0 - key_V[351:320] (Read/Write)
// 0x3c : Data signal of key_V
//        bit 31~0 - key_V[383:352] (Read/Write)
// 0x40 : Data signal of key_V
//        bit 31~0 - key_V[415:384] (Read/Write)
// 0x44 : Data signal of key_V
//        bit 31~0 - key_V[447:416] (Read/Write)
// 0x48 : Data signal of key_V
//        bit 31~0 - key_V[479:448] (Read/Write)
// 0x4c : Data signal of key_V
//        bit 31~0 - key_V[511:480] (Read/Write)
// 0x50 : reserved
// 0x54 : Data signal of output_V
//        bit 31~0 - output_V[31:0] (Read)
// 0x58 : Data signal of output_V
//        bit 31~0 - output_V[63:32] (Read)
// 0x5c : Data signal of output_V
//        bit 31~0 - output_V[95:64] (Read)
// 0x60 : Data signal of output_V
//        bit 31~0 - output_V[127:96] (Read)
// 0x64 : Data signal of output_V
//        bit 31~0 - output_V[159:128] (Read)
// 0x68 : Data signal of output_V
//        bit 31~0 - output_V[191:160] (Read)
// 0x6c : Data signal of output_V
//        bit 31~0 - output_V[223:192] (Read)
// 0x70 : Data signal of output_V
//        bit 31~0 - output_V[255:224] (Read)
// 0x74 : Data signal of output_V
//        bit 31~0 - output_V[287:256] (Read)
// 0x78 : Data signal of output_V
//        bit 31~0 - output_V[319:288] (Read)
// 0x7c : Data signal of output_V
//        bit 31~0 - output_V[351:320] (Read)
// 0x80 : Data signal of output_V
//        bit 31~0 - output_V[383:352] (Read)
// 0x84 : Data signal of output_V
//        bit 31~0 - output_V[415:384] (Read)
// 0x88 : Data signal of output_V
//        bit 31~0 - output_V[447:416] (Read)
// 0x8c : Data signal of output_V
//        bit 31~0 - output_V[479:448] (Read)
// 0x90 : Data signal of output_V
//        bit 31~0 - output_V[511:480] (Read)
// 0x94 : Control signal of output_V
//        bit 0  - output_V_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

//------------------------Parameter----------------------
localparam
    ADDR_AP_CTRL          = 8'h00,
    ADDR_GIE              = 8'h04,
    ADDR_IER              = 8'h08,
    ADDR_ISR              = 8'h0c,
    ADDR_KEY_V_DATA_0     = 8'h10,
    ADDR_KEY_V_DATA_1     = 8'h14,
    ADDR_KEY_V_DATA_2     = 8'h18,
    ADDR_KEY_V_DATA_3     = 8'h1c,
    ADDR_KEY_V_DATA_4     = 8'h20,
    ADDR_KEY_V_DATA_5     = 8'h24,
    ADDR_KEY_V_DATA_6     = 8'h28,
    ADDR_KEY_V_DATA_7     = 8'h2c,
    ADDR_KEY_V_DATA_8     = 8'h30,
    ADDR_KEY_V_DATA_9     = 8'h34,
    ADDR_KEY_V_DATA_10    = 8'h38,
    ADDR_KEY_V_DATA_11    = 8'h3c,
    ADDR_KEY_V_DATA_12    = 8'h40,
    ADDR_KEY_V_DATA_13    = 8'h44,
    ADDR_KEY_V_DATA_14    = 8'h48,
    ADDR_KEY_V_DATA_15    = 8'h4c,
    ADDR_KEY_V_CTRL       = 8'h50,
    ADDR_OUTPUT_V_DATA_0  = 8'h54,
    ADDR_OUTPUT_V_DATA_1  = 8'h58,
    ADDR_OUTPUT_V_DATA_2  = 8'h5c,
    ADDR_OUTPUT_V_DATA_3  = 8'h60,
    ADDR_OUTPUT_V_DATA_4  = 8'h64,
    ADDR_OUTPUT_V_DATA_5  = 8'h68,
    ADDR_OUTPUT_V_DATA_6  = 8'h6c,
    ADDR_OUTPUT_V_DATA_7  = 8'h70,
    ADDR_OUTPUT_V_DATA_8  = 8'h74,
    ADDR_OUTPUT_V_DATA_9  = 8'h78,
    ADDR_OUTPUT_V_DATA_10 = 8'h7c,
    ADDR_OUTPUT_V_DATA_11 = 8'h80,
    ADDR_OUTPUT_V_DATA_12 = 8'h84,
    ADDR_OUTPUT_V_DATA_13 = 8'h88,
    ADDR_OUTPUT_V_DATA_14 = 8'h8c,
    ADDR_OUTPUT_V_DATA_15 = 8'h90,
    ADDR_OUTPUT_V_CTRL    = 8'h94,
    WRIDLE                = 2'd0,
    WRDATA                = 2'd1,
    WRRESP                = 2'd2,
    RDIDLE                = 2'd0,
    RDDATA                = 2'd1,
    ADDR_BITS         = 8;

//------------------------Local signal-------------------
    reg  [1:0]                    wstate;
    reg  [1:0]                    wnext;
    reg  [ADDR_BITS-1:0]          waddr;
    wire [31:0]                   wmask;
    wire                          aw_hs;
    wire                          w_hs;
    reg  [1:0]                    rstate;
    reg  [1:0]                    rnext;
    reg  [31:0]                   rdata;
    wire                          ar_hs;
    wire [ADDR_BITS-1:0]          raddr;
    // internal registers
    wire                          int_ap_idle;
    wire                          int_ap_ready;
    reg                           int_ap_done;
    reg                           int_ap_start;
    reg                           int_auto_restart;
    reg                           int_gie;
    reg  [1:0]                    int_ier;
    reg  [1:0]                    int_isr;
    reg  [511:0]                  int_key_V;
    reg  [511:0]                  int_output_V;
    reg                           int_output_V_ap_vld;

//------------------------Instantiation------------------

//------------------------AXI write fsm------------------
assign AWREADY = (wstate == WRIDLE);
assign WREADY  = (wstate == WRDATA);
assign BRESP   = 2'b00;  // OKAY
assign BVALID  = (wstate == WRRESP);
assign wmask   = { {8{WSTRB[3]}}, {8{WSTRB[2]}}, {8{WSTRB[1]}}, {8{WSTRB[0]}} };
assign aw_hs   = AWVALID & AWREADY;
assign w_hs    = WVALID & WREADY;

// wstate
always @(posedge ACLK) begin
    if (ARESET)
        wstate <= WRIDLE;
    else if (ACLK_EN)
        wstate <= wnext;
end

// wnext
always @(*) begin
    case (wstate)
        WRIDLE:
            if (AWVALID)
                wnext = WRDATA;
            else
                wnext = WRIDLE;
        WRDATA:
            if (WVALID)
                wnext = WRRESP;
            else
                wnext = WRDATA;
        WRRESP:
            if (BREADY)
                wnext = WRIDLE;
            else
                wnext = WRRESP;
        default:
            wnext = WRIDLE;
    endcase
end

// waddr
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (aw_hs)
            waddr <= AWADDR[ADDR_BITS-1:0];
    end
end

//------------------------AXI read fsm-------------------
assign ARREADY = (rstate == RDIDLE);
assign RDATA   = rdata;
assign RRESP   = 2'b00;  // OKAY
assign RVALID  = (rstate == RDDATA);
assign ar_hs   = ARVALID & ARREADY;
assign raddr   = ARADDR[ADDR_BITS-1:0];

// rstate
always @(posedge ACLK) begin
    if (ARESET)
        rstate <= RDIDLE;
    else if (ACLK_EN)
        rstate <= rnext;
end

// rnext
always @(*) begin
    case (rstate)
        RDIDLE:
            if (ARVALID)
                rnext = RDDATA;
            else
                rnext = RDIDLE;
        RDDATA:
            if (RREADY & RVALID)
                rnext = RDIDLE;
            else
                rnext = RDDATA;
        default:
            rnext = RDIDLE;
    endcase
end

// rdata
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (ar_hs) begin
            rdata <= 1'b0;
            case (raddr)
                ADDR_AP_CTRL: begin
                    rdata[0] <= int_ap_start;
                    rdata[1] <= int_ap_done;
                    rdata[2] <= int_ap_idle;
                    rdata[3] <= int_ap_ready;
                    rdata[7] <= int_auto_restart;
                end
                ADDR_GIE: begin
                    rdata <= int_gie;
                end
                ADDR_IER: begin
                    rdata <= int_ier;
                end
                ADDR_ISR: begin
                    rdata <= int_isr;
                end
                ADDR_KEY_V_DATA_0: begin
                    rdata <= int_key_V[31:0];
                end
                ADDR_KEY_V_DATA_1: begin
                    rdata <= int_key_V[63:32];
                end
                ADDR_KEY_V_DATA_2: begin
                    rdata <= int_key_V[95:64];
                end
                ADDR_KEY_V_DATA_3: begin
                    rdata <= int_key_V[127:96];
                end
                ADDR_KEY_V_DATA_4: begin
                    rdata <= int_key_V[159:128];
                end
                ADDR_KEY_V_DATA_5: begin
                    rdata <= int_key_V[191:160];
                end
                ADDR_KEY_V_DATA_6: begin
                    rdata <= int_key_V[223:192];
                end
                ADDR_KEY_V_DATA_7: begin
                    rdata <= int_key_V[255:224];
                end
                ADDR_KEY_V_DATA_8: begin
                    rdata <= int_key_V[287:256];
                end
                ADDR_KEY_V_DATA_9: begin
                    rdata <= int_key_V[319:288];
                end
                ADDR_KEY_V_DATA_10: begin
                    rdata <= int_key_V[351:320];
                end
                ADDR_KEY_V_DATA_11: begin
                    rdata <= int_key_V[383:352];
                end
                ADDR_KEY_V_DATA_12: begin
                    rdata <= int_key_V[415:384];
                end
                ADDR_KEY_V_DATA_13: begin
                    rdata <= int_key_V[447:416];
                end
                ADDR_KEY_V_DATA_14: begin
                    rdata <= int_key_V[479:448];
                end
                ADDR_KEY_V_DATA_15: begin
                    rdata <= int_key_V[511:480];
                end
                ADDR_OUTPUT_V_DATA_0: begin
                    rdata <= int_output_V[31:0];
                end
                ADDR_OUTPUT_V_DATA_1: begin
                    rdata <= int_output_V[63:32];
                end
                ADDR_OUTPUT_V_DATA_2: begin
                    rdata <= int_output_V[95:64];
                end
                ADDR_OUTPUT_V_DATA_3: begin
                    rdata <= int_output_V[127:96];
                end
                ADDR_OUTPUT_V_DATA_4: begin
                    rdata <= int_output_V[159:128];
                end
                ADDR_OUTPUT_V_DATA_5: begin
                    rdata <= int_output_V[191:160];
                end
                ADDR_OUTPUT_V_DATA_6: begin
                    rdata <= int_output_V[223:192];
                end
                ADDR_OUTPUT_V_DATA_7: begin
                    rdata <= int_output_V[255:224];
                end
                ADDR_OUTPUT_V_DATA_8: begin
                    rdata <= int_output_V[287:256];
                end
                ADDR_OUTPUT_V_DATA_9: begin
                    rdata <= int_output_V[319:288];
                end
                ADDR_OUTPUT_V_DATA_10: begin
                    rdata <= int_output_V[351:320];
                end
                ADDR_OUTPUT_V_DATA_11: begin
                    rdata <= int_output_V[383:352];
                end
                ADDR_OUTPUT_V_DATA_12: begin
                    rdata <= int_output_V[415:384];
                end
                ADDR_OUTPUT_V_DATA_13: begin
                    rdata <= int_output_V[447:416];
                end
                ADDR_OUTPUT_V_DATA_14: begin
                    rdata <= int_output_V[479:448];
                end
                ADDR_OUTPUT_V_DATA_15: begin
                    rdata <= int_output_V[511:480];
                end
                ADDR_OUTPUT_V_CTRL: begin
                    rdata[0] <= int_output_V_ap_vld;
                end
            endcase
        end
    end
end


//------------------------Register logic-----------------
assign interrupt    = int_gie & (|int_isr);
assign ap_start     = int_ap_start;
assign int_ap_idle  = ap_idle;
assign int_ap_ready = ap_ready;
assign key_V        = int_key_V;
// int_ap_start
always @(posedge ACLK) begin
    if (ARESET)
        int_ap_start <= 1'b0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_AP_CTRL && WSTRB[0] && WDATA[0])
            int_ap_start <= 1'b1;
        else if (int_ap_ready)
            int_ap_start <= int_auto_restart; // clear on handshake/auto restart
    end
end

// int_ap_done
always @(posedge ACLK) begin
    if (ARESET)
        int_ap_done <= 1'b0;
    else if (ACLK_EN) begin
        if (ap_done)
            int_ap_done <= 1'b1;
        else if (ar_hs && raddr == ADDR_AP_CTRL)
            int_ap_done <= 1'b0; // clear on read
    end
end

// int_auto_restart
always @(posedge ACLK) begin
    if (ARESET)
        int_auto_restart <= 1'b0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_AP_CTRL && WSTRB[0])
            int_auto_restart <=  WDATA[7];
    end
end

// int_gie
always @(posedge ACLK) begin
    if (ARESET)
        int_gie <= 1'b0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_GIE && WSTRB[0])
            int_gie <= WDATA[0];
    end
end

// int_ier
always @(posedge ACLK) begin
    if (ARESET)
        int_ier <= 1'b0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_IER && WSTRB[0])
            int_ier <= WDATA[1:0];
    end
end

// int_isr[0]
always @(posedge ACLK) begin
    if (ARESET)
        int_isr[0] <= 1'b0;
    else if (ACLK_EN) begin
        if (int_ier[0] & ap_done)
            int_isr[0] <= 1'b1;
        else if (w_hs && waddr == ADDR_ISR && WSTRB[0])
            int_isr[0] <= int_isr[0] ^ WDATA[0]; // toggle on write
    end
end

// int_isr[1]
always @(posedge ACLK) begin
    if (ARESET)
        int_isr[1] <= 1'b0;
    else if (ACLK_EN) begin
        if (int_ier[1] & ap_ready)
            int_isr[1] <= 1'b1;
        else if (w_hs && waddr == ADDR_ISR && WSTRB[0])
            int_isr[1] <= int_isr[1] ^ WDATA[1]; // toggle on write
    end
end

// int_key_V[31:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[31:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_0)
            int_key_V[31:0] <= (WDATA[31:0] & wmask) | (int_key_V[31:0] & ~wmask);
    end
end

// int_key_V[63:32]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[63:32] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_1)
            int_key_V[63:32] <= (WDATA[31:0] & wmask) | (int_key_V[63:32] & ~wmask);
    end
end

// int_key_V[95:64]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[95:64] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_2)
            int_key_V[95:64] <= (WDATA[31:0] & wmask) | (int_key_V[95:64] & ~wmask);
    end
end

// int_key_V[127:96]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[127:96] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_3)
            int_key_V[127:96] <= (WDATA[31:0] & wmask) | (int_key_V[127:96] & ~wmask);
    end
end

// int_key_V[159:128]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[159:128] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_4)
            int_key_V[159:128] <= (WDATA[31:0] & wmask) | (int_key_V[159:128] & ~wmask);
    end
end

// int_key_V[191:160]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[191:160] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_5)
            int_key_V[191:160] <= (WDATA[31:0] & wmask) | (int_key_V[191:160] & ~wmask);
    end
end

// int_key_V[223:192]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[223:192] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_6)
            int_key_V[223:192] <= (WDATA[31:0] & wmask) | (int_key_V[223:192] & ~wmask);
    end
end

// int_key_V[255:224]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[255:224] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_7)
            int_key_V[255:224] <= (WDATA[31:0] & wmask) | (int_key_V[255:224] & ~wmask);
    end
end

// int_key_V[287:256]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[287:256] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_8)
            int_key_V[287:256] <= (WDATA[31:0] & wmask) | (int_key_V[287:256] & ~wmask);
    end
end

// int_key_V[319:288]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[319:288] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_9)
            int_key_V[319:288] <= (WDATA[31:0] & wmask) | (int_key_V[319:288] & ~wmask);
    end
end

// int_key_V[351:320]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[351:320] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_10)
            int_key_V[351:320] <= (WDATA[31:0] & wmask) | (int_key_V[351:320] & ~wmask);
    end
end

// int_key_V[383:352]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[383:352] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_11)
            int_key_V[383:352] <= (WDATA[31:0] & wmask) | (int_key_V[383:352] & ~wmask);
    end
end

// int_key_V[415:384]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[415:384] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_12)
            int_key_V[415:384] <= (WDATA[31:0] & wmask) | (int_key_V[415:384] & ~wmask);
    end
end

// int_key_V[447:416]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[447:416] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_13)
            int_key_V[447:416] <= (WDATA[31:0] & wmask) | (int_key_V[447:416] & ~wmask);
    end
end

// int_key_V[479:448]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[479:448] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_14)
            int_key_V[479:448] <= (WDATA[31:0] & wmask) | (int_key_V[479:448] & ~wmask);
    end
end

// int_key_V[511:480]
always @(posedge ACLK) begin
    if (ARESET)
        int_key_V[511:480] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_KEY_V_DATA_15)
            int_key_V[511:480] <= (WDATA[31:0] & wmask) | (int_key_V[511:480] & ~wmask);
    end
end

// int_output_V
always @(posedge ACLK) begin
    if (ARESET)
        int_output_V <= 0;
    else if (ACLK_EN) begin
        if (output_V_ap_vld)
            int_output_V <= output_V;
    end
end

// int_output_V_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_output_V_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (output_V_ap_vld)
            int_output_V_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_OUTPUT_V_CTRL)
            int_output_V_ap_vld <= 1'b0; // clear on read
    end
end


//------------------------Memory logic-------------------

endmodule
