// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// PERIPH_BUS
// 0x000 : Control signals
//         bit 0  - ap_start (Read/Write/SC)
//         bit 1  - ap_done (Read/COR)
//         bit 2  - ap_idle (Read)
//         bit 3  - ap_ready (Read)
//         bit 7  - auto_restart (Read/Write)
//         others - reserved
// 0x004 : Global Interrupt Enable Register
//         bit 0  - Global Interrupt Enable (Read/Write)
//         others - reserved
// 0x008 : IP Interrupt Enable Register (Read/Write)
//         bit 0  - Channel 0 (ap_done)
//         others - reserved
// 0x00c : IP Interrupt Status Register (Read/TOW)
//         bit 0  - Channel 0 (ap_done)
//         others - reserved
// 0x010 : Data signal of number1_V
//         bit 31~0 - number1_V[31:0] (Read/Write)
// 0x014 : Data signal of number1_V
//         bit 31~0 - number1_V[63:32] (Read/Write)
// 0x018 : Data signal of number1_V
//         bit 31~0 - number1_V[95:64] (Read/Write)
// 0x01c : Data signal of number1_V
//         bit 31~0 - number1_V[127:96] (Read/Write)
// 0x020 : Data signal of number1_V
//         bit 31~0 - number1_V[159:128] (Read/Write)
// 0x024 : Data signal of number1_V
//         bit 31~0 - number1_V[191:160] (Read/Write)
// 0x028 : Data signal of number1_V
//         bit 31~0 - number1_V[223:192] (Read/Write)
// 0x02c : Data signal of number1_V
//         bit 31~0 - number1_V[255:224] (Read/Write)
// 0x030 : Data signal of number1_V
//         bit 31~0 - number1_V[287:256] (Read/Write)
// 0x034 : Data signal of number1_V
//         bit 31~0 - number1_V[319:288] (Read/Write)
// 0x038 : Data signal of number1_V
//         bit 31~0 - number1_V[351:320] (Read/Write)
// 0x03c : Data signal of number1_V
//         bit 31~0 - number1_V[383:352] (Read/Write)
// 0x040 : Data signal of number1_V
//         bit 31~0 - number1_V[415:384] (Read/Write)
// 0x044 : Data signal of number1_V
//         bit 31~0 - number1_V[447:416] (Read/Write)
// 0x048 : Data signal of number1_V
//         bit 31~0 - number1_V[479:448] (Read/Write)
// 0x04c : Data signal of number1_V
//         bit 31~0 - number1_V[511:480] (Read/Write)
// 0x050 : Data signal of number1_V
//         bit 31~0 - number1_V[543:512] (Read/Write)
// 0x054 : Data signal of number1_V
//         bit 31~0 - number1_V[575:544] (Read/Write)
// 0x058 : Data signal of number1_V
//         bit 31~0 - number1_V[607:576] (Read/Write)
// 0x05c : Data signal of number1_V
//         bit 31~0 - number1_V[639:608] (Read/Write)
// 0x060 : Data signal of number1_V
//         bit 31~0 - number1_V[671:640] (Read/Write)
// 0x064 : Data signal of number1_V
//         bit 31~0 - number1_V[703:672] (Read/Write)
// 0x068 : Data signal of number1_V
//         bit 31~0 - number1_V[735:704] (Read/Write)
// 0x06c : Data signal of number1_V
//         bit 31~0 - number1_V[767:736] (Read/Write)
// 0x070 : Data signal of number1_V
//         bit 31~0 - number1_V[799:768] (Read/Write)
// 0x074 : Data signal of number1_V
//         bit 31~0 - number1_V[831:800] (Read/Write)
// 0x078 : Data signal of number1_V
//         bit 31~0 - number1_V[863:832] (Read/Write)
// 0x07c : Data signal of number1_V
//         bit 31~0 - number1_V[895:864] (Read/Write)
// 0x080 : Data signal of number1_V
//         bit 31~0 - number1_V[927:896] (Read/Write)
// 0x084 : Data signal of number1_V
//         bit 31~0 - number1_V[959:928] (Read/Write)
// 0x088 : Data signal of number1_V
//         bit 31~0 - number1_V[991:960] (Read/Write)
// 0x08c : Data signal of number1_V
//         bit 31~0 - number1_V[1023:992] (Read/Write)
// 0x090 : Data signal of number1_V
//         bit 31~0 - number1_V[1055:1024] (Read/Write)
// 0x094 : Data signal of number1_V
//         bit 31~0 - number1_V[1087:1056] (Read/Write)
// 0x098 : Data signal of number1_V
//         bit 31~0 - number1_V[1119:1088] (Read/Write)
// 0x09c : Data signal of number1_V
//         bit 31~0 - number1_V[1151:1120] (Read/Write)
// 0x0a0 : Data signal of number1_V
//         bit 31~0 - number1_V[1183:1152] (Read/Write)
// 0x0a4 : Data signal of number1_V
//         bit 31~0 - number1_V[1215:1184] (Read/Write)
// 0x0a8 : Data signal of number1_V
//         bit 31~0 - number1_V[1247:1216] (Read/Write)
// 0x0ac : Data signal of number1_V
//         bit 31~0 - number1_V[1279:1248] (Read/Write)
// 0x0b0 : Data signal of number1_V
//         bit 31~0 - number1_V[1311:1280] (Read/Write)
// 0x0b4 : Data signal of number1_V
//         bit 31~0 - number1_V[1343:1312] (Read/Write)
// 0x0b8 : Data signal of number1_V
//         bit 31~0 - number1_V[1375:1344] (Read/Write)
// 0x0bc : Data signal of number1_V
//         bit 31~0 - number1_V[1407:1376] (Read/Write)
// 0x0c0 : Data signal of number1_V
//         bit 31~0 - number1_V[1439:1408] (Read/Write)
// 0x0c4 : Data signal of number1_V
//         bit 31~0 - number1_V[1471:1440] (Read/Write)
// 0x0c8 : Data signal of number1_V
//         bit 31~0 - number1_V[1503:1472] (Read/Write)
// 0x0cc : Data signal of number1_V
//         bit 31~0 - number1_V[1535:1504] (Read/Write)
// 0x0d0 : Data signal of number1_V
//         bit 31~0 - number1_V[1567:1536] (Read/Write)
// 0x0d4 : Data signal of number1_V
//         bit 31~0 - number1_V[1599:1568] (Read/Write)
// 0x0d8 : Data signal of number1_V
//         bit 31~0 - number1_V[1631:1600] (Read/Write)
// 0x0dc : Data signal of number1_V
//         bit 31~0 - number1_V[1663:1632] (Read/Write)
// 0x0e0 : Data signal of number1_V
//         bit 31~0 - number1_V[1695:1664] (Read/Write)
// 0x0e4 : Data signal of number1_V
//         bit 31~0 - number1_V[1727:1696] (Read/Write)
// 0x0e8 : Data signal of number1_V
//         bit 31~0 - number1_V[1759:1728] (Read/Write)
// 0x0ec : Data signal of number1_V
//         bit 31~0 - number1_V[1791:1760] (Read/Write)
// 0x0f0 : Data signal of number1_V
//         bit 31~0 - number1_V[1823:1792] (Read/Write)
// 0x0f4 : Data signal of number1_V
//         bit 31~0 - number1_V[1855:1824] (Read/Write)
// 0x0f8 : Data signal of number1_V
//         bit 31~0 - number1_V[1887:1856] (Read/Write)
// 0x0fc : Data signal of number1_V
//         bit 31~0 - number1_V[1919:1888] (Read/Write)
// 0x100 : Data signal of number1_V
//         bit 31~0 - number1_V[1951:1920] (Read/Write)
// 0x104 : Data signal of number1_V
//         bit 31~0 - number1_V[1983:1952] (Read/Write)
// 0x108 : Data signal of number1_V
//         bit 31~0 - number1_V[2015:1984] (Read/Write)
// 0x10c : Data signal of number1_V
//         bit 31~0 - number1_V[2047:2016] (Read/Write)
// 0x110 : reserved
// 0x114 : Data signal of number2_V
//         bit 31~0 - number2_V[31:0] (Read/Write)
// 0x118 : Data signal of number2_V
//         bit 31~0 - number2_V[63:32] (Read/Write)
// 0x11c : Data signal of number2_V
//         bit 31~0 - number2_V[95:64] (Read/Write)
// 0x120 : Data signal of number2_V
//         bit 31~0 - number2_V[127:96] (Read/Write)
// 0x124 : Data signal of number2_V
//         bit 31~0 - number2_V[159:128] (Read/Write)
// 0x128 : Data signal of number2_V
//         bit 31~0 - number2_V[191:160] (Read/Write)
// 0x12c : Data signal of number2_V
//         bit 31~0 - number2_V[223:192] (Read/Write)
// 0x130 : Data signal of number2_V
//         bit 31~0 - number2_V[255:224] (Read/Write)
// 0x134 : Data signal of number2_V
//         bit 31~0 - number2_V[287:256] (Read/Write)
// 0x138 : Data signal of number2_V
//         bit 31~0 - number2_V[319:288] (Read/Write)
// 0x13c : Data signal of number2_V
//         bit 31~0 - number2_V[351:320] (Read/Write)
// 0x140 : Data signal of number2_V
//         bit 31~0 - number2_V[383:352] (Read/Write)
// 0x144 : Data signal of number2_V
//         bit 31~0 - number2_V[415:384] (Read/Write)
// 0x148 : Data signal of number2_V
//         bit 31~0 - number2_V[447:416] (Read/Write)
// 0x14c : Data signal of number2_V
//         bit 31~0 - number2_V[479:448] (Read/Write)
// 0x150 : Data signal of number2_V
//         bit 31~0 - number2_V[511:480] (Read/Write)
// 0x154 : Data signal of number2_V
//         bit 31~0 - number2_V[543:512] (Read/Write)
// 0x158 : Data signal of number2_V
//         bit 31~0 - number2_V[575:544] (Read/Write)
// 0x15c : Data signal of number2_V
//         bit 31~0 - number2_V[607:576] (Read/Write)
// 0x160 : Data signal of number2_V
//         bit 31~0 - number2_V[639:608] (Read/Write)
// 0x164 : Data signal of number2_V
//         bit 31~0 - number2_V[671:640] (Read/Write)
// 0x168 : Data signal of number2_V
//         bit 31~0 - number2_V[703:672] (Read/Write)
// 0x16c : Data signal of number2_V
//         bit 31~0 - number2_V[735:704] (Read/Write)
// 0x170 : Data signal of number2_V
//         bit 31~0 - number2_V[767:736] (Read/Write)
// 0x174 : Data signal of number2_V
//         bit 31~0 - number2_V[799:768] (Read/Write)
// 0x178 : Data signal of number2_V
//         bit 31~0 - number2_V[831:800] (Read/Write)
// 0x17c : Data signal of number2_V
//         bit 31~0 - number2_V[863:832] (Read/Write)
// 0x180 : Data signal of number2_V
//         bit 31~0 - number2_V[895:864] (Read/Write)
// 0x184 : Data signal of number2_V
//         bit 31~0 - number2_V[927:896] (Read/Write)
// 0x188 : Data signal of number2_V
//         bit 31~0 - number2_V[959:928] (Read/Write)
// 0x18c : Data signal of number2_V
//         bit 31~0 - number2_V[991:960] (Read/Write)
// 0x190 : Data signal of number2_V
//         bit 31~0 - number2_V[1023:992] (Read/Write)
// 0x194 : Data signal of number2_V
//         bit 31~0 - number2_V[1055:1024] (Read/Write)
// 0x198 : Data signal of number2_V
//         bit 31~0 - number2_V[1087:1056] (Read/Write)
// 0x19c : Data signal of number2_V
//         bit 31~0 - number2_V[1119:1088] (Read/Write)
// 0x1a0 : Data signal of number2_V
//         bit 31~0 - number2_V[1151:1120] (Read/Write)
// 0x1a4 : Data signal of number2_V
//         bit 31~0 - number2_V[1183:1152] (Read/Write)
// 0x1a8 : Data signal of number2_V
//         bit 31~0 - number2_V[1215:1184] (Read/Write)
// 0x1ac : Data signal of number2_V
//         bit 31~0 - number2_V[1247:1216] (Read/Write)
// 0x1b0 : Data signal of number2_V
//         bit 31~0 - number2_V[1279:1248] (Read/Write)
// 0x1b4 : Data signal of number2_V
//         bit 31~0 - number2_V[1311:1280] (Read/Write)
// 0x1b8 : Data signal of number2_V
//         bit 31~0 - number2_V[1343:1312] (Read/Write)
// 0x1bc : Data signal of number2_V
//         bit 31~0 - number2_V[1375:1344] (Read/Write)
// 0x1c0 : Data signal of number2_V
//         bit 31~0 - number2_V[1407:1376] (Read/Write)
// 0x1c4 : Data signal of number2_V
//         bit 31~0 - number2_V[1439:1408] (Read/Write)
// 0x1c8 : Data signal of number2_V
//         bit 31~0 - number2_V[1471:1440] (Read/Write)
// 0x1cc : Data signal of number2_V
//         bit 31~0 - number2_V[1503:1472] (Read/Write)
// 0x1d0 : Data signal of number2_V
//         bit 31~0 - number2_V[1535:1504] (Read/Write)
// 0x1d4 : Data signal of number2_V
//         bit 31~0 - number2_V[1567:1536] (Read/Write)
// 0x1d8 : Data signal of number2_V
//         bit 31~0 - number2_V[1599:1568] (Read/Write)
// 0x1dc : Data signal of number2_V
//         bit 31~0 - number2_V[1631:1600] (Read/Write)
// 0x1e0 : Data signal of number2_V
//         bit 31~0 - number2_V[1663:1632] (Read/Write)
// 0x1e4 : Data signal of number2_V
//         bit 31~0 - number2_V[1695:1664] (Read/Write)
// 0x1e8 : Data signal of number2_V
//         bit 31~0 - number2_V[1727:1696] (Read/Write)
// 0x1ec : Data signal of number2_V
//         bit 31~0 - number2_V[1759:1728] (Read/Write)
// 0x1f0 : Data signal of number2_V
//         bit 31~0 - number2_V[1791:1760] (Read/Write)
// 0x1f4 : Data signal of number2_V
//         bit 31~0 - number2_V[1823:1792] (Read/Write)
// 0x1f8 : Data signal of number2_V
//         bit 31~0 - number2_V[1855:1824] (Read/Write)
// 0x1fc : Data signal of number2_V
//         bit 31~0 - number2_V[1887:1856] (Read/Write)
// 0x200 : Data signal of number2_V
//         bit 31~0 - number2_V[1919:1888] (Read/Write)
// 0x204 : Data signal of number2_V
//         bit 31~0 - number2_V[1951:1920] (Read/Write)
// 0x208 : Data signal of number2_V
//         bit 31~0 - number2_V[1983:1952] (Read/Write)
// 0x20c : Data signal of number2_V
//         bit 31~0 - number2_V[2015:1984] (Read/Write)
// 0x210 : Data signal of number2_V
//         bit 31~0 - number2_V[2047:2016] (Read/Write)
// 0x214 : reserved
// 0x218 : Data signal of output_V
//         bit 31~0 - output_V[31:0] (Read)
// 0x21c : Data signal of output_V
//         bit 31~0 - output_V[63:32] (Read)
// 0x220 : Data signal of output_V
//         bit 31~0 - output_V[95:64] (Read)
// 0x224 : Data signal of output_V
//         bit 31~0 - output_V[127:96] (Read)
// 0x228 : Data signal of output_V
//         bit 31~0 - output_V[159:128] (Read)
// 0x22c : Data signal of output_V
//         bit 31~0 - output_V[191:160] (Read)
// 0x230 : Data signal of output_V
//         bit 31~0 - output_V[223:192] (Read)
// 0x234 : Data signal of output_V
//         bit 31~0 - output_V[255:224] (Read)
// 0x238 : Data signal of output_V
//         bit 31~0 - output_V[287:256] (Read)
// 0x23c : Data signal of output_V
//         bit 31~0 - output_V[319:288] (Read)
// 0x240 : Data signal of output_V
//         bit 31~0 - output_V[351:320] (Read)
// 0x244 : Data signal of output_V
//         bit 31~0 - output_V[383:352] (Read)
// 0x248 : Data signal of output_V
//         bit 31~0 - output_V[415:384] (Read)
// 0x24c : Data signal of output_V
//         bit 31~0 - output_V[447:416] (Read)
// 0x250 : Data signal of output_V
//         bit 31~0 - output_V[479:448] (Read)
// 0x254 : Data signal of output_V
//         bit 31~0 - output_V[511:480] (Read)
// 0x258 : Data signal of output_V
//         bit 31~0 - output_V[543:512] (Read)
// 0x25c : Data signal of output_V
//         bit 31~0 - output_V[575:544] (Read)
// 0x260 : Data signal of output_V
//         bit 31~0 - output_V[607:576] (Read)
// 0x264 : Data signal of output_V
//         bit 31~0 - output_V[639:608] (Read)
// 0x268 : Data signal of output_V
//         bit 31~0 - output_V[671:640] (Read)
// 0x26c : Data signal of output_V
//         bit 31~0 - output_V[703:672] (Read)
// 0x270 : Data signal of output_V
//         bit 31~0 - output_V[735:704] (Read)
// 0x274 : Data signal of output_V
//         bit 31~0 - output_V[767:736] (Read)
// 0x278 : Data signal of output_V
//         bit 31~0 - output_V[799:768] (Read)
// 0x27c : Data signal of output_V
//         bit 31~0 - output_V[831:800] (Read)
// 0x280 : Data signal of output_V
//         bit 31~0 - output_V[863:832] (Read)
// 0x284 : Data signal of output_V
//         bit 31~0 - output_V[895:864] (Read)
// 0x288 : Data signal of output_V
//         bit 31~0 - output_V[927:896] (Read)
// 0x28c : Data signal of output_V
//         bit 31~0 - output_V[959:928] (Read)
// 0x290 : Data signal of output_V
//         bit 31~0 - output_V[991:960] (Read)
// 0x294 : Data signal of output_V
//         bit 31~0 - output_V[1023:992] (Read)
// 0x298 : Data signal of output_V
//         bit 31~0 - output_V[1055:1024] (Read)
// 0x29c : Data signal of output_V
//         bit 31~0 - output_V[1087:1056] (Read)
// 0x2a0 : Data signal of output_V
//         bit 31~0 - output_V[1119:1088] (Read)
// 0x2a4 : Data signal of output_V
//         bit 31~0 - output_V[1151:1120] (Read)
// 0x2a8 : Data signal of output_V
//         bit 31~0 - output_V[1183:1152] (Read)
// 0x2ac : Data signal of output_V
//         bit 31~0 - output_V[1215:1184] (Read)
// 0x2b0 : Data signal of output_V
//         bit 31~0 - output_V[1247:1216] (Read)
// 0x2b4 : Data signal of output_V
//         bit 31~0 - output_V[1279:1248] (Read)
// 0x2b8 : Data signal of output_V
//         bit 31~0 - output_V[1311:1280] (Read)
// 0x2bc : Data signal of output_V
//         bit 31~0 - output_V[1343:1312] (Read)
// 0x2c0 : Data signal of output_V
//         bit 31~0 - output_V[1375:1344] (Read)
// 0x2c4 : Data signal of output_V
//         bit 31~0 - output_V[1407:1376] (Read)
// 0x2c8 : Data signal of output_V
//         bit 31~0 - output_V[1439:1408] (Read)
// 0x2cc : Data signal of output_V
//         bit 31~0 - output_V[1471:1440] (Read)
// 0x2d0 : Data signal of output_V
//         bit 31~0 - output_V[1503:1472] (Read)
// 0x2d4 : Data signal of output_V
//         bit 31~0 - output_V[1535:1504] (Read)
// 0x2d8 : Data signal of output_V
//         bit 31~0 - output_V[1567:1536] (Read)
// 0x2dc : Data signal of output_V
//         bit 31~0 - output_V[1599:1568] (Read)
// 0x2e0 : Data signal of output_V
//         bit 31~0 - output_V[1631:1600] (Read)
// 0x2e4 : Data signal of output_V
//         bit 31~0 - output_V[1663:1632] (Read)
// 0x2e8 : Data signal of output_V
//         bit 31~0 - output_V[1695:1664] (Read)
// 0x2ec : Data signal of output_V
//         bit 31~0 - output_V[1727:1696] (Read)
// 0x2f0 : Data signal of output_V
//         bit 31~0 - output_V[1759:1728] (Read)
// 0x2f4 : Data signal of output_V
//         bit 31~0 - output_V[1791:1760] (Read)
// 0x2f8 : Data signal of output_V
//         bit 31~0 - output_V[1823:1792] (Read)
// 0x2fc : Data signal of output_V
//         bit 31~0 - output_V[1855:1824] (Read)
// 0x300 : Data signal of output_V
//         bit 31~0 - output_V[1887:1856] (Read)
// 0x304 : Data signal of output_V
//         bit 31~0 - output_V[1919:1888] (Read)
// 0x308 : Data signal of output_V
//         bit 31~0 - output_V[1951:1920] (Read)
// 0x30c : Data signal of output_V
//         bit 31~0 - output_V[1983:1952] (Read)
// 0x310 : Data signal of output_V
//         bit 31~0 - output_V[2015:1984] (Read)
// 0x314 : Data signal of output_V
//         bit 31~0 - output_V[2047:2016] (Read)
// 0x318 : Control signal of output_V
//         bit 0  - output_V_ap_vld (Read/COR)
//         others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBIGINT_MATH_PERIPH_BUS_ADDR_AP_CTRL         0x000
#define XBIGINT_MATH_PERIPH_BUS_ADDR_GIE             0x004
#define XBIGINT_MATH_PERIPH_BUS_ADDR_IER             0x008
#define XBIGINT_MATH_PERIPH_BUS_ADDR_ISR             0x00c
#define XBIGINT_MATH_PERIPH_BUS_ADDR_NUMBER1_V_DATA  0x010
#define XBIGINT_MATH_PERIPH_BUS_BITS_NUMBER1_V_DATA  2048
#define XBIGINT_MATH_PERIPH_BUS_ADDR_NUMBER1_V_DATA_ 0x038
#define XBIGINT_MATH_PERIPH_BUS_BITS_NUMBER1_V_DATA  2048
#define XBIGINT_MATH_PERIPH_BUS_ADDR_NUMBER2_V_DATA  0x114
#define XBIGINT_MATH_PERIPH_BUS_BITS_NUMBER2_V_DATA  2048
#define XBIGINT_MATH_PERIPH_BUS_ADDR_NUMBER2_V_DATA_ 0x13c
#define XBIGINT_MATH_PERIPH_BUS_BITS_NUMBER2_V_DATA  2048
#define XBIGINT_MATH_PERIPH_BUS_ADDR_OUTPUT_V_DATA   0x218
#define XBIGINT_MATH_PERIPH_BUS_BITS_OUTPUT_V_DATA   2048
#define XBIGINT_MATH_PERIPH_BUS_ADDR_OUTPUT_V_DATA_  0x240
#define XBIGINT_MATH_PERIPH_BUS_BITS_OUTPUT_V_DATA   2048
#define XBIGINT_MATH_PERIPH_BUS_ADDR_OUTPUT_V_CTRL   0x318

