#pragma line 1 "BigInt/solution1/main.c" ::: -10
#pragma line 1 "BigInt/solution1/main.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "BigInt/solution1/main.c" 2 ::: 184
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 185
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 213
#pragma line 128 "/usr/include/features.h" 3 4 ::: 314
#pragma line 149 "/usr/include/features.h" 3 4 ::: 328
#pragma line 177 "/usr/include/features.h" 3 4 ::: 330
#pragma line 193 "/usr/include/features.h" 3 4 ::: 333
#pragma line 350 "/usr/include/features.h" 3 4 ::: 364
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 368
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 403
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 409
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 432
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 473
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 479
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 497
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 503
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 507
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 509
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 513
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 576
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 617
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 638
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 662
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 663
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 665
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 667
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 668
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 693
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 704
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 709
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 710
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 711
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 717
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 758
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 761
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 763
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 791
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 793
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 795
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 856
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 863
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 881
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 886
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 897
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 966
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 980
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 983
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 984
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1016
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1032
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1057
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1060
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1065
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1087
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1108
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1111
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1122
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1132
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1134
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1138
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1187
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1188
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1194
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1196
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1220
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1231
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1272
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1274
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1296
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1322
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1326
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1341
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1353
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1359
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1361
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1371
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1393
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1409
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1426
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1458
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1504
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1518
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1521
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1597
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1636
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1677
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1790
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1853
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1902
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1913
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1943
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1971
#pragma line 910 "/usr/include/stdio.h" 3 4 ::: 2004
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2016
#pragma line 2 "BigInt/solution1/main.c" 2 ::: 2019
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2020
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2053
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2078
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2081
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2091
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2120
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2138
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2139
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2195
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2196
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2233
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2235
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2239
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2242
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2260
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2261
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2263
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2265
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2273
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2291
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2294
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2297
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2299
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2300
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2334
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2340
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2356
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2358
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2480
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2494
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2515
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2532
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2554
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2562
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2571
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2572
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2593
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2596
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2599
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2602
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2605
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2606
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2607
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2632
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2635
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2645
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2680
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2711
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2734
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2736
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2738
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2739
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2743
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2783
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2794
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2815
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2823
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2825
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2860
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2905
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2935
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2939
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2957
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2968
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2970
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2992
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 2996
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3018
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3020
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3022
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3023
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3046
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3066
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3136
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3167
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3168
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3311
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3340
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3365
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3390
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3393
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3402
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3415
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3422
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3434
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3445
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 3492
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 3501
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 3508
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 3514
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 3529
#pragma line 912 "/usr/include/stdlib.h" 3 4 ::: 3680
#pragma line 948 "/usr/include/stdlib.h" 3 4 ::: 3682
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 3691
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 3709
#pragma line 3 "BigInt/solution1/main.c" 2 ::: 3712
#pragma line 1 "/home/linux/Documents/DLA/bigint/./bigint.h" 1 ::: 3713
#pragma line 4 "BigInt/solution1/main.c" 2 ::: 3750
