#pragma line 1 "BigInt/solution1/main.c" ::: 0
#pragma line 1 "BigInt/solution1/main.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "BigInt/solution1/main.c" 2 ::: 194
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 223
#pragma line 128 "/usr/include/features.h" 3 4 ::: 324
#pragma line 149 "/usr/include/features.h" 3 4 ::: 338
#pragma line 177 "/usr/include/features.h" 3 4 ::: 340
#pragma line 193 "/usr/include/features.h" 3 4 ::: 343
#pragma line 350 "/usr/include/features.h" 3 4 ::: 374
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 378
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 413
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 419
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 442
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 483
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 489
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 507
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 513
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 517
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 519
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 533
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 586
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 627
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 648
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 672
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 673
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 675
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 677
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 678
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 703
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 714
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 719
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 720
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 721
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 727
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 768
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 771
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 773
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 801
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 803
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 805
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 866
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 873
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 891
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 896
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 907
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 976
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 990
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 993
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 994
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1026
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1042
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1067
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1070
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1075
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1097
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1118
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1121
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1132
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1142
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1144
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1148
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1197
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1198
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1204
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1206
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1230
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1241
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1282
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1284
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1306
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1332
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1336
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1351
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1363
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1369
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1371
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1381
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1403
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1419
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1436
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1468
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1514
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1528
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1531
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1607
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1646
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1687
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1800
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1863
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1912
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1923
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1953
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1981
#pragma line 910 "/usr/include/stdio.h" 3 4 ::: 2014
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2026
#pragma line 2 "BigInt/solution1/main.c" 2 ::: 2029
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2030
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2063
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2088
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2091
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2101
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2130
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2148
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2149
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2205
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2206
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2243
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2245
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2249
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2252
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2270
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2271
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2273
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2275
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2283
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2301
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2304
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2307
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2309
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2310
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2344
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2350
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2366
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2368
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2490
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2504
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2525
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2542
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2564
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2572
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2581
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2582
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2603
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2606
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2609
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2612
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2615
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2616
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2617
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2642
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2645
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2655
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2690
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2721
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2744
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2746
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2748
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2749
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2753
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2793
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2804
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2825
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2833
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2835
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2870
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2915
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2945
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2949
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2967
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2978
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2980
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3002
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3006
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3028
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3030
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3032
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3033
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3056
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3076
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3146
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3177
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3178
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3321
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3350
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3375
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3400
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3403
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3412
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3425
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3432
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3444
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3455
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 3502
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 3511
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 3518
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 3524
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 3539
#pragma line 912 "/usr/include/stdlib.h" 3 4 ::: 3690
#pragma line 948 "/usr/include/stdlib.h" 3 4 ::: 3692
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 3701
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 3719
#pragma line 3 "BigInt/solution1/main.c" 2 ::: 3722
#pragma line 1 "/home/linux/Documents/DLA/bigint/./bigint.h" 1 ::: 3723
#pragma line 4 "BigInt/solution1/main.c" 2 ::: 3760
