// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "bigint_math_bigint_mul.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic bigint_math_bigint_mul::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic bigint_math_bigint_mul::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st1_fsm_0 = "1";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st2_fsm_1 = "10";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st3_fsm_2 = "100";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st4_fsm_3 = "1000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st5_fsm_4 = "10000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st6_fsm_5 = "100000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<21> bigint_math_bigint_mul::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> bigint_math_bigint_mul::ap_const_lv1_1 = "1";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_B = "1011";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_F = "1111";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_2 = "10";
const sc_lv<1> bigint_math_bigint_mul::ap_const_lv1_0 = "0";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_4 = "100";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_7 = "111";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_8 = "1000";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_9 = "1001";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_A = "1010";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_C = "1100";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_E = "1110";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_10 = "10000";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_11 = "10001";
const sc_lv<9> bigint_math_bigint_mul::ap_const_lv9_0 = "000000000";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_1 = "1";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_3 = "11";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_5 = "101";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_6 = "110";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_14 = "10100";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_12 = "10010";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_13 = "10011";
const sc_lv<32> bigint_math_bigint_mul::ap_const_lv32_D = "1101";
const sc_lv<8> bigint_math_bigint_mul::ap_const_lv8_1 = "1";
const sc_lv<9> bigint_math_bigint_mul::ap_const_lv9_1FF = "111111111";
const sc_lv<9> bigint_math_bigint_mul::ap_const_lv9_100 = "100000000";
const sc_lv<9> bigint_math_bigint_mul::ap_const_lv9_1 = "1";
const sc_lv<9> bigint_math_bigint_mul::ap_const_lv9_FF = "11111111";
const sc_lv<8> bigint_math_bigint_mul::ap_const_lv8_0 = "00000000";
const sc_lv<10> bigint_math_bigint_mul::ap_const_lv10_3FE = "1111111110";

bigint_math_bigint_mul::bigint_math_bigint_mul(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sum_U = new bigint_math_bigint_add_tempA("sum_U");
    sum_U->clk(ap_clk);
    sum_U->reset(ap_rst);
    sum_U->address0(sum_address0);
    sum_U->ce0(sum_ce0);
    sum_U->we0(sum_we0);
    sum_U->d0(sum_d0);
    sum_U->q0(sum_q0);
    tempA_U = new bigint_math_bigint_add_tempA("tempA_U");
    tempA_U->clk(ap_clk);
    tempA_U->reset(ap_rst);
    tempA_U->address0(tempA_address0);
    tempA_U->ce0(tempA_ce0);
    tempA_U->we0(tempA_we0);
    tempA_U->d0(tempA_d0);
    tempA_U->q0(tempA_q0);
    tempB_U = new bigint_math_bigint_add_tempA("tempB_U");
    tempB_U->clk(ap_clk);
    tempB_U->reset(ap_rst);
    tempB_U->address0(tempB_address0);
    tempB_U->ce0(tempB_ce0);
    tempB_U->we0(tempB_we0);
    tempB_U->d0(tempB_d0);
    tempB_U->q0(tempB_q0);
    grp_bigint_math_bigint_add_1_fu_210 = new bigint_math_bigint_add_1("grp_bigint_math_bigint_add_1_fu_210");
    grp_bigint_math_bigint_add_1_fu_210->ap_clk(ap_clk);
    grp_bigint_math_bigint_add_1_fu_210->ap_rst(ap_rst);
    grp_bigint_math_bigint_add_1_fu_210->ap_start(grp_bigint_math_bigint_add_1_fu_210_ap_start);
    grp_bigint_math_bigint_add_1_fu_210->ap_done(grp_bigint_math_bigint_add_1_fu_210_ap_done);
    grp_bigint_math_bigint_add_1_fu_210->ap_idle(grp_bigint_math_bigint_add_1_fu_210_ap_idle);
    grp_bigint_math_bigint_add_1_fu_210->ap_ready(grp_bigint_math_bigint_add_1_fu_210_ap_ready);
    grp_bigint_math_bigint_add_1_fu_210->out_r_address0(grp_bigint_math_bigint_add_1_fu_210_out_r_address0);
    grp_bigint_math_bigint_add_1_fu_210->out_r_ce0(grp_bigint_math_bigint_add_1_fu_210_out_r_ce0);
    grp_bigint_math_bigint_add_1_fu_210->out_r_we0(grp_bigint_math_bigint_add_1_fu_210_out_r_we0);
    grp_bigint_math_bigint_add_1_fu_210->out_r_d0(grp_bigint_math_bigint_add_1_fu_210_out_r_d0);
    grp_bigint_math_bigint_add_1_fu_210->out_r_q0(out_r_q0);
    grp_bigint_math_bigint_add_1_fu_210->b_address0(grp_bigint_math_bigint_add_1_fu_210_b_address0);
    grp_bigint_math_bigint_add_1_fu_210->b_ce0(grp_bigint_math_bigint_add_1_fu_210_b_ce0);
    grp_bigint_math_bigint_add_1_fu_210->b_q0(sum_q0);
    grp_bigint_math_bigint_zero_fu_217 = new bigint_math_bigint_zero("grp_bigint_math_bigint_zero_fu_217");
    grp_bigint_math_bigint_zero_fu_217->ap_clk(ap_clk);
    grp_bigint_math_bigint_zero_fu_217->ap_rst(ap_rst);
    grp_bigint_math_bigint_zero_fu_217->ap_start(grp_bigint_math_bigint_zero_fu_217_ap_start);
    grp_bigint_math_bigint_zero_fu_217->ap_done(grp_bigint_math_bigint_zero_fu_217_ap_done);
    grp_bigint_math_bigint_zero_fu_217->ap_idle(grp_bigint_math_bigint_zero_fu_217_ap_idle);
    grp_bigint_math_bigint_zero_fu_217->ap_ready(grp_bigint_math_bigint_zero_fu_217_ap_ready);
    grp_bigint_math_bigint_zero_fu_217->in_r_address0(grp_bigint_math_bigint_zero_fu_217_in_r_address0);
    grp_bigint_math_bigint_zero_fu_217->in_r_ce0(grp_bigint_math_bigint_zero_fu_217_in_r_ce0);
    grp_bigint_math_bigint_zero_fu_217->in_r_we0(grp_bigint_math_bigint_zero_fu_217_in_r_we0);
    grp_bigint_math_bigint_zero_fu_217->in_r_d0(grp_bigint_math_bigint_zero_fu_217_in_r_d0);
    grp_bigint_math_bigint_zero_fu_223 = new bigint_math_bigint_zero("grp_bigint_math_bigint_zero_fu_223");
    grp_bigint_math_bigint_zero_fu_223->ap_clk(ap_clk);
    grp_bigint_math_bigint_zero_fu_223->ap_rst(ap_rst);
    grp_bigint_math_bigint_zero_fu_223->ap_start(grp_bigint_math_bigint_zero_fu_223_ap_start);
    grp_bigint_math_bigint_zero_fu_223->ap_done(grp_bigint_math_bigint_zero_fu_223_ap_done);
    grp_bigint_math_bigint_zero_fu_223->ap_idle(grp_bigint_math_bigint_zero_fu_223_ap_idle);
    grp_bigint_math_bigint_zero_fu_223->ap_ready(grp_bigint_math_bigint_zero_fu_223_ap_ready);
    grp_bigint_math_bigint_zero_fu_223->in_r_address0(grp_bigint_math_bigint_zero_fu_223_in_r_address0);
    grp_bigint_math_bigint_zero_fu_223->in_r_ce0(grp_bigint_math_bigint_zero_fu_223_in_r_ce0);
    grp_bigint_math_bigint_zero_fu_223->in_r_we0(grp_bigint_math_bigint_zero_fu_223_in_r_we0);
    grp_bigint_math_bigint_zero_fu_223->in_r_d0(grp_bigint_math_bigint_zero_fu_223_in_r_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_i_fu_259_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond1_fu_281_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond1_fu_281_p2 );

    SC_METHOD(thread_ap_sig_101);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_117);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_133);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_144);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_158);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_182);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_191);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_207);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_216);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_282);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_294);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_303);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_314);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_322);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_339);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_354);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_381);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_67);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_74);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_84);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_144 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_158 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_67 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_182 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_381 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_191 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_74 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_207 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_216 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_339 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_38 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_354 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_322 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_282 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_84 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_294 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_101 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_303 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_314 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_117 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_133 );

    SC_METHOD(thread_b_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_i5_fu_276_p1 );

    SC_METHOD(thread_b_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_carry_fu_345_p4);
    sensitive << ( tmp_34_fu_340_p2 );

    SC_METHOD(thread_exitcond1_fu_281_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( i_reg_178 );

    SC_METHOD(thread_exitcond_fu_308_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( j_reg_189 );

    SC_METHOD(thread_exitcond_i4_fu_264_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( i_i3_reg_167 );

    SC_METHOD(thread_exitcond_i_fu_247_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( i_i_reg_156 );

    SC_METHOD(thread_grp_bigint_math_bigint_add_1_fu_210_ap_start);
    sensitive << ( ap_reg_grp_bigint_math_bigint_add_1_fu_210_ap_start );

    SC_METHOD(thread_grp_bigint_math_bigint_zero_fu_217_ap_start);
    sensitive << ( ap_reg_grp_bigint_math_bigint_zero_fu_217_ap_start );

    SC_METHOD(thread_grp_bigint_math_bigint_zero_fu_223_ap_start);
    sensitive << ( ap_reg_grp_bigint_math_bigint_zero_fu_223_ap_start );

    SC_METHOD(thread_grp_fu_230_p2);
    sensitive << ( sum_q0 );

    SC_METHOD(thread_grp_fu_237_p2);
    sensitive << ( k5_reg_200 );

    SC_METHOD(thread_i_4_fu_287_p2);
    sensitive << ( i_reg_178 );

    SC_METHOD(thread_i_8_fu_253_p2);
    sensitive << ( i_i_reg_156 );

    SC_METHOD(thread_i_9_fu_270_p2);
    sensitive << ( i_i3_reg_167 );

    SC_METHOD(thread_j_5_fu_314_p2);
    sensitive << ( j_reg_189 );

    SC_METHOD(thread_k5_cast_fu_435_p1);
    sensitive << ( k5_reg_200 );

    SC_METHOD(thread_k_fu_293_p2);
    sensitive << ( i_reg_178 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( grp_bigint_math_bigint_add_1_fu_210_out_r_address0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( grp_bigint_math_bigint_add_1_fu_210_out_r_ce0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( grp_bigint_math_bigint_add_1_fu_210_out_r_d0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( grp_bigint_math_bigint_add_1_fu_210_out_r_we0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );

    SC_METHOD(thread_prod_fu_331_p1);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tempA_q0 );

    SC_METHOD(thread_prod_fu_331_p2);
    sensitive << ( tempB_load_reg_509 );
    sensitive << ( prod_fu_331_p1 );

    SC_METHOD(thread_sum_address0);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( sum_addr_1_reg_548 );
    sensitive << ( sum_addr_2_reg_557 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( sum_addr_3_reg_567 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( sum_addr_reg_576 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( grp_bigint_math_bigint_add_1_fu_210_b_address0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_address0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_in_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( tmp_38_fu_367_p1 );
    sensitive << ( tmp_42_fu_399_p1 );
    sensitive << ( tmp_s_fu_409_p1 );
    sensitive << ( tmp_48_fu_445_p1 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_sum_ce0);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( grp_bigint_math_bigint_add_1_fu_210_b_ce0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_ce0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_in_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_sum_d0);
    sensitive << ( tmp_44_reg_562 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( tmp_50_reg_581 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_d0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_in_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( grp_fu_230_p2 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_sum_we0);
    sensitive << ( tmp_37_reg_544 );
    sensitive << ( tmp_9_reg_553 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( tmp_10_reg_572 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_we0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_in_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_tempA_address0);
    sensitive << ( tmp_i_reg_463 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_32_fu_326_p1 );

    SC_METHOD(thread_tempA_ce0);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tempA_d0);
    sensitive << ( a_q0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tempA_we0);
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_in_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tempB_address0);
    sensitive << ( tmp_i5_reg_481 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_in_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_fu_299_p1 );

    SC_METHOD(thread_tempB_ce0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_in_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tempB_d0);
    sensitive << ( b_q0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_in_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tempB_we0);
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_in_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tmp_10_fu_427_p3);
    sensitive << ( tmp_46_fu_421_p2 );

    SC_METHOD(thread_tmp_31_fu_320_p2);
    sensitive << ( j_reg_189 );

    SC_METHOD(thread_tmp_32_fu_326_p1);
    sensitive << ( tmp_31_fu_320_p2 );

    SC_METHOD(thread_tmp_33_cast_fu_336_p0);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tempA_q0 );

    SC_METHOD(thread_tmp_34_fu_340_p0);
    sensitive << ( tmp_cast_reg_514 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_tmp_34_fu_340_p1);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_34_fu_340_p10 );

    SC_METHOD(thread_tmp_34_fu_340_p10);
    sensitive << ( tmp_33_cast_fu_336_p0 );

    SC_METHOD(thread_tmp_34_fu_340_p2);
    sensitive << ( tmp_34_fu_340_p0 );
    sensitive << ( tmp_34_fu_340_p1 );

    SC_METHOD(thread_tmp_36_fu_355_p2);
    sensitive << ( prod_fu_331_p2 );
    sensitive << ( carry_fu_345_p4 );

    SC_METHOD(thread_tmp_37_fu_361_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_36_fu_355_p2 );

    SC_METHOD(thread_tmp_38_fu_367_p1);
    sensitive << ( k5_reg_200 );

    SC_METHOD(thread_tmp_39_cast_fu_372_p1);
    sensitive << ( sum_q0 );

    SC_METHOD(thread_tmp_40_cast_fu_376_p1);
    sensitive << ( prod_reg_532 );

    SC_METHOD(thread_tmp_40_fu_379_p2);
    sensitive << ( tmp_39_cast_fu_372_p1 );
    sensitive << ( tmp_40_cast_fu_376_p1 );

    SC_METHOD(thread_tmp_41_fu_393_p2);
    sensitive << ( k5_reg_200 );

    SC_METHOD(thread_tmp_42_fu_399_p1);
    sensitive << ( tmp_41_fu_393_p2 );

    SC_METHOD(thread_tmp_44_fu_404_p2);
    sensitive << ( reg_243 );
    sensitive << ( prod_reg_532 );

    SC_METHOD(thread_tmp_46_fu_421_p2);
    sensitive << ( tmp_51_cast_fu_414_p1 );
    sensitive << ( tmp_52_cast_fu_418_p1 );

    SC_METHOD(thread_tmp_47_fu_439_p2);
    sensitive << ( k5_cast_fu_435_p1 );

    SC_METHOD(thread_tmp_48_fu_445_p1);
    sensitive << ( tmp_47_fu_439_p2 );

    SC_METHOD(thread_tmp_50_fu_450_p2);
    sensitive << ( reg_243 );
    sensitive << ( carry_reg_538 );

    SC_METHOD(thread_tmp_51_cast_fu_414_p1);
    sensitive << ( sum_q0 );

    SC_METHOD(thread_tmp_52_cast_fu_418_p1);
    sensitive << ( carry_reg_538 );

    SC_METHOD(thread_tmp_9_fu_385_p3);
    sensitive << ( tmp_40_fu_379_p2 );

    SC_METHOD(thread_tmp_cast_fu_304_p0);
    sensitive << ( tempB_q0 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_tmp_cast_fu_304_p1);
    sensitive << ( tmp_cast_fu_304_p0 );

    SC_METHOD(thread_tmp_fu_299_p1);
    sensitive << ( k_fu_293_p2 );

    SC_METHOD(thread_tmp_i5_fu_276_p1);
    sensitive << ( i_i3_reg_167 );

    SC_METHOD(thread_tmp_i_fu_259_p1);
    sensitive << ( i_i_reg_156 );

    SC_METHOD(thread_tmp_s_fu_409_p1);
    sensitive << ( grp_fu_237_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_i_fu_247_p2 );
    sensitive << ( exitcond_i4_fu_264_p2 );
    sensitive << ( exitcond1_fu_281_p2 );
    sensitive << ( exitcond_fu_308_p2 );
    sensitive << ( tmp_37_fu_361_p2 );
    sensitive << ( grp_bigint_math_bigint_add_1_fu_210_ap_done );
    sensitive << ( grp_bigint_math_bigint_zero_fu_217_ap_done );
    sensitive << ( grp_bigint_math_bigint_zero_fu_223_ap_done );

    ap_CS_fsm = "000000000000000000001";
    ap_reg_grp_bigint_math_bigint_add_1_fu_210_ap_start = SC_LOGIC_0;
    ap_reg_grp_bigint_math_bigint_zero_fu_217_ap_start = SC_LOGIC_0;
    ap_reg_grp_bigint_math_bigint_zero_fu_223_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "bigint_math_bigint_mul_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
    sc_trace(mVcdFile, out_r_q0, "(port)out_r_q0");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, b_address0, "(port)b_address0");
    sc_trace(mVcdFile, b_ce0, "(port)b_ce0");
    sc_trace(mVcdFile, b_q0, "(port)b_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_38, "ap_sig_38");
    sc_trace(mVcdFile, sum_q0, "sum_q0");
    sc_trace(mVcdFile, reg_243, "reg_243");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_67, "ap_sig_67");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_74, "ap_sig_74");
    sc_trace(mVcdFile, i_8_fu_253_p2, "i_8_fu_253_p2");
    sc_trace(mVcdFile, i_8_reg_458, "i_8_reg_458");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_84, "ap_sig_84");
    sc_trace(mVcdFile, tmp_i_fu_259_p1, "tmp_i_fu_259_p1");
    sc_trace(mVcdFile, tmp_i_reg_463, "tmp_i_reg_463");
    sc_trace(mVcdFile, exitcond_i_fu_247_p2, "exitcond_i_fu_247_p2");
    sc_trace(mVcdFile, i_9_fu_270_p2, "i_9_fu_270_p2");
    sc_trace(mVcdFile, i_9_reg_476, "i_9_reg_476");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_101, "ap_sig_101");
    sc_trace(mVcdFile, tmp_i5_fu_276_p1, "tmp_i5_fu_276_p1");
    sc_trace(mVcdFile, tmp_i5_reg_481, "tmp_i5_reg_481");
    sc_trace(mVcdFile, exitcond_i4_fu_264_p2, "exitcond_i4_fu_264_p2");
    sc_trace(mVcdFile, i_4_fu_287_p2, "i_4_fu_287_p2");
    sc_trace(mVcdFile, i_4_reg_494, "i_4_reg_494");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_117, "ap_sig_117");
    sc_trace(mVcdFile, k_fu_293_p2, "k_fu_293_p2");
    sc_trace(mVcdFile, k_reg_499, "k_reg_499");
    sc_trace(mVcdFile, exitcond1_fu_281_p2, "exitcond1_fu_281_p2");
    sc_trace(mVcdFile, tempB_q0, "tempB_q0");
    sc_trace(mVcdFile, tempB_load_reg_509, "tempB_load_reg_509");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_133, "ap_sig_133");
    sc_trace(mVcdFile, tmp_cast_fu_304_p1, "tmp_cast_fu_304_p1");
    sc_trace(mVcdFile, tmp_cast_reg_514, "tmp_cast_reg_514");
    sc_trace(mVcdFile, j_5_fu_314_p2, "j_5_fu_314_p2");
    sc_trace(mVcdFile, j_5_reg_522, "j_5_reg_522");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_144, "ap_sig_144");
    sc_trace(mVcdFile, exitcond_fu_308_p2, "exitcond_fu_308_p2");
    sc_trace(mVcdFile, prod_fu_331_p2, "prod_fu_331_p2");
    sc_trace(mVcdFile, prod_reg_532, "prod_reg_532");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_158, "ap_sig_158");
    sc_trace(mVcdFile, carry_fu_345_p4, "carry_fu_345_p4");
    sc_trace(mVcdFile, carry_reg_538, "carry_reg_538");
    sc_trace(mVcdFile, tmp_37_fu_361_p2, "tmp_37_fu_361_p2");
    sc_trace(mVcdFile, tmp_37_reg_544, "tmp_37_reg_544");
    sc_trace(mVcdFile, sum_addr_1_reg_548, "sum_addr_1_reg_548");
    sc_trace(mVcdFile, tmp_9_fu_385_p3, "tmp_9_fu_385_p3");
    sc_trace(mVcdFile, tmp_9_reg_553, "tmp_9_reg_553");
    sc_trace(mVcdFile, sum_addr_2_reg_557, "sum_addr_2_reg_557");
    sc_trace(mVcdFile, tmp_44_fu_404_p2, "tmp_44_fu_404_p2");
    sc_trace(mVcdFile, tmp_44_reg_562, "tmp_44_reg_562");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_182, "ap_sig_182");
    sc_trace(mVcdFile, sum_addr_3_reg_567, "sum_addr_3_reg_567");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_191, "ap_sig_191");
    sc_trace(mVcdFile, tmp_10_fu_427_p3, "tmp_10_fu_427_p3");
    sc_trace(mVcdFile, tmp_10_reg_572, "tmp_10_reg_572");
    sc_trace(mVcdFile, sum_addr_reg_576, "sum_addr_reg_576");
    sc_trace(mVcdFile, tmp_50_fu_450_p2, "tmp_50_fu_450_p2");
    sc_trace(mVcdFile, tmp_50_reg_581, "tmp_50_reg_581");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_207, "ap_sig_207");
    sc_trace(mVcdFile, grp_fu_237_p2, "grp_fu_237_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_216, "ap_sig_216");
    sc_trace(mVcdFile, sum_address0, "sum_address0");
    sc_trace(mVcdFile, sum_ce0, "sum_ce0");
    sc_trace(mVcdFile, sum_we0, "sum_we0");
    sc_trace(mVcdFile, sum_d0, "sum_d0");
    sc_trace(mVcdFile, tempA_address0, "tempA_address0");
    sc_trace(mVcdFile, tempA_ce0, "tempA_ce0");
    sc_trace(mVcdFile, tempA_we0, "tempA_we0");
    sc_trace(mVcdFile, tempA_d0, "tempA_d0");
    sc_trace(mVcdFile, tempA_q0, "tempA_q0");
    sc_trace(mVcdFile, tempB_address0, "tempB_address0");
    sc_trace(mVcdFile, tempB_ce0, "tempB_ce0");
    sc_trace(mVcdFile, tempB_we0, "tempB_we0");
    sc_trace(mVcdFile, tempB_d0, "tempB_d0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_ap_start, "grp_bigint_math_bigint_add_1_fu_210_ap_start");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_ap_done, "grp_bigint_math_bigint_add_1_fu_210_ap_done");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_ap_idle, "grp_bigint_math_bigint_add_1_fu_210_ap_idle");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_ap_ready, "grp_bigint_math_bigint_add_1_fu_210_ap_ready");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_out_r_address0, "grp_bigint_math_bigint_add_1_fu_210_out_r_address0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_out_r_ce0, "grp_bigint_math_bigint_add_1_fu_210_out_r_ce0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_out_r_we0, "grp_bigint_math_bigint_add_1_fu_210_out_r_we0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_out_r_d0, "grp_bigint_math_bigint_add_1_fu_210_out_r_d0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_b_address0, "grp_bigint_math_bigint_add_1_fu_210_b_address0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_add_1_fu_210_b_ce0, "grp_bigint_math_bigint_add_1_fu_210_b_ce0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_217_ap_start, "grp_bigint_math_bigint_zero_fu_217_ap_start");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_217_ap_done, "grp_bigint_math_bigint_zero_fu_217_ap_done");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_217_ap_idle, "grp_bigint_math_bigint_zero_fu_217_ap_idle");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_217_ap_ready, "grp_bigint_math_bigint_zero_fu_217_ap_ready");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_217_in_r_address0, "grp_bigint_math_bigint_zero_fu_217_in_r_address0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_217_in_r_ce0, "grp_bigint_math_bigint_zero_fu_217_in_r_ce0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_217_in_r_we0, "grp_bigint_math_bigint_zero_fu_217_in_r_we0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_217_in_r_d0, "grp_bigint_math_bigint_zero_fu_217_in_r_d0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_223_ap_start, "grp_bigint_math_bigint_zero_fu_223_ap_start");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_223_ap_done, "grp_bigint_math_bigint_zero_fu_223_ap_done");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_223_ap_idle, "grp_bigint_math_bigint_zero_fu_223_ap_idle");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_223_ap_ready, "grp_bigint_math_bigint_zero_fu_223_ap_ready");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_223_in_r_address0, "grp_bigint_math_bigint_zero_fu_223_in_r_address0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_223_in_r_ce0, "grp_bigint_math_bigint_zero_fu_223_in_r_ce0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_223_in_r_we0, "grp_bigint_math_bigint_zero_fu_223_in_r_we0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_223_in_r_d0, "grp_bigint_math_bigint_zero_fu_223_in_r_d0");
    sc_trace(mVcdFile, i_i_reg_156, "i_i_reg_156");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_282, "ap_sig_282");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_294, "ap_sig_294");
    sc_trace(mVcdFile, i_i3_reg_167, "i_i3_reg_167");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_303, "ap_sig_303");
    sc_trace(mVcdFile, i_reg_178, "i_reg_178");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_314, "ap_sig_314");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_322, "ap_sig_322");
    sc_trace(mVcdFile, j_reg_189, "j_reg_189");
    sc_trace(mVcdFile, k5_reg_200, "k5_reg_200");
    sc_trace(mVcdFile, ap_reg_grp_bigint_math_bigint_add_1_fu_210_ap_start, "ap_reg_grp_bigint_math_bigint_add_1_fu_210_ap_start");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_339, "ap_sig_339");
    sc_trace(mVcdFile, ap_reg_grp_bigint_math_bigint_zero_fu_217_ap_start, "ap_reg_grp_bigint_math_bigint_zero_fu_217_ap_start");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_354, "ap_sig_354");
    sc_trace(mVcdFile, ap_reg_grp_bigint_math_bigint_zero_fu_223_ap_start, "ap_reg_grp_bigint_math_bigint_zero_fu_223_ap_start");
    sc_trace(mVcdFile, tmp_fu_299_p1, "tmp_fu_299_p1");
    sc_trace(mVcdFile, tmp_32_fu_326_p1, "tmp_32_fu_326_p1");
    sc_trace(mVcdFile, tmp_38_fu_367_p1, "tmp_38_fu_367_p1");
    sc_trace(mVcdFile, tmp_42_fu_399_p1, "tmp_42_fu_399_p1");
    sc_trace(mVcdFile, tmp_s_fu_409_p1, "tmp_s_fu_409_p1");
    sc_trace(mVcdFile, tmp_48_fu_445_p1, "tmp_48_fu_445_p1");
    sc_trace(mVcdFile, grp_fu_230_p2, "grp_fu_230_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_381, "ap_sig_381");
    sc_trace(mVcdFile, tmp_cast_fu_304_p0, "tmp_cast_fu_304_p0");
    sc_trace(mVcdFile, tmp_31_fu_320_p2, "tmp_31_fu_320_p2");
    sc_trace(mVcdFile, prod_fu_331_p1, "prod_fu_331_p1");
    sc_trace(mVcdFile, tmp_33_cast_fu_336_p0, "tmp_33_cast_fu_336_p0");
    sc_trace(mVcdFile, tmp_34_fu_340_p0, "tmp_34_fu_340_p0");
    sc_trace(mVcdFile, tmp_34_fu_340_p1, "tmp_34_fu_340_p1");
    sc_trace(mVcdFile, tmp_34_fu_340_p2, "tmp_34_fu_340_p2");
    sc_trace(mVcdFile, tmp_36_fu_355_p2, "tmp_36_fu_355_p2");
    sc_trace(mVcdFile, tmp_39_cast_fu_372_p1, "tmp_39_cast_fu_372_p1");
    sc_trace(mVcdFile, tmp_40_cast_fu_376_p1, "tmp_40_cast_fu_376_p1");
    sc_trace(mVcdFile, tmp_40_fu_379_p2, "tmp_40_fu_379_p2");
    sc_trace(mVcdFile, tmp_41_fu_393_p2, "tmp_41_fu_393_p2");
    sc_trace(mVcdFile, tmp_51_cast_fu_414_p1, "tmp_51_cast_fu_414_p1");
    sc_trace(mVcdFile, tmp_52_cast_fu_418_p1, "tmp_52_cast_fu_418_p1");
    sc_trace(mVcdFile, tmp_46_fu_421_p2, "tmp_46_fu_421_p2");
    sc_trace(mVcdFile, k5_cast_fu_435_p1, "k5_cast_fu_435_p1");
    sc_trace(mVcdFile, tmp_47_fu_439_p2, "tmp_47_fu_439_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, tmp_34_fu_340_p10, "tmp_34_fu_340_p10");
#endif

    }
}

bigint_math_bigint_mul::~bigint_math_bigint_mul() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sum_U;
    delete tempA_U;
    delete tempB_U;
    delete grp_bigint_math_bigint_add_1_fu_210;
    delete grp_bigint_math_bigint_zero_fu_217;
    delete grp_bigint_math_bigint_zero_fu_223;
}

void bigint_math_bigint_mul::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_bigint_math_bigint_add_1_fu_210_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_308_p2.read()))) {
            ap_reg_grp_bigint_math_bigint_add_1_fu_210_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_bigint_math_bigint_add_1_fu_210_ap_ready.read())) {
            ap_reg_grp_bigint_math_bigint_add_1_fu_210_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_bigint_math_bigint_zero_fu_217_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
              !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
              !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i4_fu_264_p2.read())) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
            ap_reg_grp_bigint_math_bigint_zero_fu_217_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_bigint_math_bigint_zero_fu_217_ap_ready.read())) {
            ap_reg_grp_bigint_math_bigint_zero_fu_217_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_bigint_math_bigint_zero_fu_223_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
              !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
              !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i4_fu_264_p2.read())))) {
            ap_reg_grp_bigint_math_bigint_zero_fu_223_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_bigint_math_bigint_zero_fu_223_ap_ready.read())) {
            ap_reg_grp_bigint_math_bigint_zero_fu_223_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(exitcond_i_fu_247_p2.read(), ap_const_lv1_0))) {
        i_i3_reg_167 = ap_const_lv9_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        i_i3_reg_167 = i_9_reg_476.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_i_reg_156 = i_8_reg_458.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_217_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_223_ap_done.read())))) {
        i_i_reg_156 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_217_ap_done.read()))) {
        i_reg_178 = i_4_reg_494.read();
    } else if ((!(esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_217_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_223_ap_done.read())) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        i_reg_178 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        j_reg_189 = j_5_reg_522.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        j_reg_189 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        k5_reg_200 = grp_fu_237_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        k5_reg_200 = k_reg_499.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        carry_reg_538 = tmp_34_fu_340_p2.read().range(15, 8);
        prod_reg_532 = prod_fu_331_p2.read();
        tmp_37_reg_544 = tmp_37_fu_361_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        i_4_reg_494 = i_4_fu_287_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_8_reg_458 = i_8_fu_253_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        i_9_reg_476 = i_9_fu_270_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        j_5_reg_522 = j_5_fu_314_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_281_p2.read()))) {
        k_reg_499 = k_fu_293_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()))) {
        reg_243 = sum_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_37_fu_361_p2.read()))) {
        sum_addr_1_reg_548 =  (sc_lv<8>) (tmp_38_fu_367_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_385_p3.read()))) {
        sum_addr_2_reg_557 =  (sc_lv<8>) (tmp_42_fu_399_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        sum_addr_3_reg_567 =  (sc_lv<8>) (tmp_s_fu_409_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_10_fu_427_p3.read()))) {
        sum_addr_reg_576 =  (sc_lv<8>) (tmp_48_fu_445_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        tempB_load_reg_509 = tempB_q0.read();
        tmp_cast_reg_514 = tmp_cast_fu_304_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        tmp_10_reg_572 = tmp_46_fu_421_p2.read().range(8, 8);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        tmp_44_reg_562 = tmp_44_fu_404_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        tmp_50_reg_581 = tmp_50_fu_450_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        tmp_9_reg_553 = tmp_40_fu_379_p2.read().range(8, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i4_fu_264_p2.read()))) {
        tmp_i5_reg_481 = tmp_i5_fu_276_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_i_fu_247_p2.read(), ap_const_lv1_0))) {
        tmp_i_reg_463 = tmp_i_fu_259_p1.read();
    }
}

void bigint_math_bigint_mul::thread_a_address0() {
    a_address0 =  (sc_lv<8>) (tmp_i_fu_259_p1.read());
}

void bigint_math_bigint_mul::thread_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_281_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_281_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_101() {
    ap_sig_101 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void bigint_math_bigint_mul::thread_ap_sig_117() {
    ap_sig_117 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void bigint_math_bigint_mul::thread_ap_sig_133() {
    ap_sig_133 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void bigint_math_bigint_mul::thread_ap_sig_144() {
    ap_sig_144 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void bigint_math_bigint_mul::thread_ap_sig_158() {
    ap_sig_158 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void bigint_math_bigint_mul::thread_ap_sig_182() {
    ap_sig_182 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void bigint_math_bigint_mul::thread_ap_sig_191() {
    ap_sig_191 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void bigint_math_bigint_mul::thread_ap_sig_207() {
    ap_sig_207 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void bigint_math_bigint_mul::thread_ap_sig_216() {
    ap_sig_216 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void bigint_math_bigint_mul::thread_ap_sig_282() {
    ap_sig_282 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void bigint_math_bigint_mul::thread_ap_sig_294() {
    ap_sig_294 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void bigint_math_bigint_mul::thread_ap_sig_303() {
    ap_sig_303 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void bigint_math_bigint_mul::thread_ap_sig_314() {
    ap_sig_314 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void bigint_math_bigint_mul::thread_ap_sig_322() {
    ap_sig_322 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void bigint_math_bigint_mul::thread_ap_sig_339() {
    ap_sig_339 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void bigint_math_bigint_mul::thread_ap_sig_354() {
    ap_sig_354 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void bigint_math_bigint_mul::thread_ap_sig_38() {
    ap_sig_38 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void bigint_math_bigint_mul::thread_ap_sig_381() {
    ap_sig_381 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void bigint_math_bigint_mul::thread_ap_sig_67() {
    ap_sig_67 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void bigint_math_bigint_mul::thread_ap_sig_74() {
    ap_sig_74 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void bigint_math_bigint_mul::thread_ap_sig_84() {
    ap_sig_84 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_144.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_158.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_67.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_182.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_381.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_191.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_74.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_207.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_216.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_339.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_38.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_354.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_322.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_282.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_84.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_294.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_101.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_303.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_314.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_117.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_133.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_b_address0() {
    b_address0 =  (sc_lv<8>) (tmp_i5_fu_276_p1.read());
}

void bigint_math_bigint_mul::thread_b_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        b_ce0 = ap_const_logic_1;
    } else {
        b_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_carry_fu_345_p4() {
    carry_fu_345_p4 = tmp_34_fu_340_p2.read().range(15, 8);
}

void bigint_math_bigint_mul::thread_exitcond1_fu_281_p2() {
    exitcond1_fu_281_p2 = (!i_reg_178.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_178.read() == ap_const_lv9_100);
}

void bigint_math_bigint_mul::thread_exitcond_fu_308_p2() {
    exitcond_fu_308_p2 = (!j_reg_189.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_189.read() == ap_const_lv9_100);
}

void bigint_math_bigint_mul::thread_exitcond_i4_fu_264_p2() {
    exitcond_i4_fu_264_p2 = (!i_i3_reg_167.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_i3_reg_167.read() == ap_const_lv9_100);
}

void bigint_math_bigint_mul::thread_exitcond_i_fu_247_p2() {
    exitcond_i_fu_247_p2 = (!i_i_reg_156.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_156.read() == ap_const_lv9_100);
}

void bigint_math_bigint_mul::thread_grp_bigint_math_bigint_add_1_fu_210_ap_start() {
    grp_bigint_math_bigint_add_1_fu_210_ap_start = ap_reg_grp_bigint_math_bigint_add_1_fu_210_ap_start.read();
}

void bigint_math_bigint_mul::thread_grp_bigint_math_bigint_zero_fu_217_ap_start() {
    grp_bigint_math_bigint_zero_fu_217_ap_start = ap_reg_grp_bigint_math_bigint_zero_fu_217_ap_start.read();
}

void bigint_math_bigint_mul::thread_grp_bigint_math_bigint_zero_fu_223_ap_start() {
    grp_bigint_math_bigint_zero_fu_223_ap_start = ap_reg_grp_bigint_math_bigint_zero_fu_223_ap_start.read();
}

void bigint_math_bigint_mul::thread_grp_fu_230_p2() {
    grp_fu_230_p2 = (!ap_const_lv8_1.is_01() || !sum_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(sum_q0.read()));
}

void bigint_math_bigint_mul::thread_grp_fu_237_p2() {
    grp_fu_237_p2 = (!k5_reg_200.read().is_01() || !ap_const_lv9_1FF.is_01())? sc_lv<9>(): (sc_biguint<9>(k5_reg_200.read()) + sc_bigint<9>(ap_const_lv9_1FF));
}

void bigint_math_bigint_mul::thread_i_4_fu_287_p2() {
    i_4_fu_287_p2 = (!i_reg_178.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_178.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void bigint_math_bigint_mul::thread_i_8_fu_253_p2() {
    i_8_fu_253_p2 = (!i_i_reg_156.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_i_reg_156.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void bigint_math_bigint_mul::thread_i_9_fu_270_p2() {
    i_9_fu_270_p2 = (!i_i3_reg_167.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_i3_reg_167.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void bigint_math_bigint_mul::thread_j_5_fu_314_p2() {
    j_5_fu_314_p2 = (!j_reg_189.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(j_reg_189.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void bigint_math_bigint_mul::thread_k5_cast_fu_435_p1() {
    k5_cast_fu_435_p1 = esl_sext<10,9>(k5_reg_200.read());
}

void bigint_math_bigint_mul::thread_k_fu_293_p2() {
    k_fu_293_p2 = (!ap_const_lv9_FF.is_01() || !i_reg_178.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_FF) - sc_biguint<9>(i_reg_178.read()));
}

void bigint_math_bigint_mul::thread_out_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        out_r_address0 = grp_bigint_math_bigint_zero_fu_217_in_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        out_r_address0 = grp_bigint_math_bigint_add_1_fu_210_out_r_address0.read();
    } else {
        out_r_address0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_mul::thread_out_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        out_r_ce0 = grp_bigint_math_bigint_zero_fu_217_in_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        out_r_ce0 = grp_bigint_math_bigint_add_1_fu_210_out_r_ce0.read();
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_out_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        out_r_d0 = grp_bigint_math_bigint_zero_fu_217_in_r_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        out_r_d0 = grp_bigint_math_bigint_add_1_fu_210_out_r_d0.read();
    } else {
        out_r_d0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_mul::thread_out_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        out_r_we0 = grp_bigint_math_bigint_zero_fu_217_in_r_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        out_r_we0 = grp_bigint_math_bigint_add_1_fu_210_out_r_we0.read();
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_prod_fu_331_p1() {
    prod_fu_331_p1 = tempA_q0.read();
}

void bigint_math_bigint_mul::thread_prod_fu_331_p2() {
    prod_fu_331_p2 = (!tempB_load_reg_509.read().is_01() || !prod_fu_331_p1.read().is_01())? sc_lv<8>(): sc_bigint<8>(tempB_load_reg_509.read()) * sc_bigint<8>(prod_fu_331_p1.read());
}

void bigint_math_bigint_mul::thread_sum_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        sum_address0 = sum_addr_3_reg_567.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        sum_address0 = sum_addr_reg_576.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        sum_address0 = sum_addr_1_reg_548.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        sum_address0 = sum_addr_2_reg_557.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        sum_address0 =  (sc_lv<8>) (tmp_48_fu_445_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        sum_address0 =  (sc_lv<8>) (tmp_s_fu_409_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        sum_address0 =  (sc_lv<8>) (tmp_42_fu_399_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        sum_address0 =  (sc_lv<8>) (tmp_38_fu_367_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        sum_address0 = grp_bigint_math_bigint_zero_fu_223_in_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        sum_address0 = grp_bigint_math_bigint_zero_fu_217_in_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        sum_address0 = grp_bigint_math_bigint_add_1_fu_210_b_address0.read();
    } else {
        sum_address0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_mul::thread_sum_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        sum_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        sum_ce0 = grp_bigint_math_bigint_zero_fu_223_in_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        sum_ce0 = grp_bigint_math_bigint_zero_fu_217_in_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        sum_ce0 = grp_bigint_math_bigint_add_1_fu_210_b_ce0.read();
    } else {
        sum_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_sum_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        sum_d0 = tmp_50_reg_581.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        sum_d0 = tmp_44_reg_562.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        sum_d0 = grp_fu_230_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        sum_d0 = grp_bigint_math_bigint_zero_fu_223_in_r_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        sum_d0 = grp_bigint_math_bigint_zero_fu_217_in_r_d0.read();
    } else {
        sum_d0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_mul::thread_sum_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_reg_553.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_10_reg_572.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_37_reg_544.read())))) {
        sum_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        sum_we0 = grp_bigint_math_bigint_zero_fu_223_in_r_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        sum_we0 = grp_bigint_math_bigint_zero_fu_217_in_r_we0.read();
    } else {
        sum_we0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_tempA_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        tempA_address0 =  (sc_lv<8>) (tmp_i_reg_463.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        tempA_address0 =  (sc_lv<8>) (tmp_32_fu_326_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempA_address0 = grp_bigint_math_bigint_zero_fu_217_in_r_address0.read();
    } else {
        tempA_address0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_mul::thread_tempA_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        tempA_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempA_ce0 = grp_bigint_math_bigint_zero_fu_217_in_r_ce0.read();
    } else {
        tempA_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_tempA_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        tempA_d0 = a_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempA_d0 = grp_bigint_math_bigint_zero_fu_217_in_r_d0.read();
    } else {
        tempA_d0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_mul::thread_tempA_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        tempA_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempA_we0 = grp_bigint_math_bigint_zero_fu_217_in_r_we0.read();
    } else {
        tempA_we0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_tempB_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        tempB_address0 =  (sc_lv<8>) (tmp_i5_reg_481.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        tempB_address0 =  (sc_lv<8>) (tmp_fu_299_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempB_address0 = grp_bigint_math_bigint_zero_fu_223_in_r_address0.read();
    } else {
        tempB_address0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_mul::thread_tempB_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        tempB_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempB_ce0 = grp_bigint_math_bigint_zero_fu_223_in_r_ce0.read();
    } else {
        tempB_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_tempB_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        tempB_d0 = b_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempB_d0 = grp_bigint_math_bigint_zero_fu_223_in_r_d0.read();
    } else {
        tempB_d0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_mul::thread_tempB_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        tempB_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempB_we0 = grp_bigint_math_bigint_zero_fu_223_in_r_we0.read();
    } else {
        tempB_we0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_mul::thread_tmp_10_fu_427_p3() {
    tmp_10_fu_427_p3 = tmp_46_fu_421_p2.read().range(8, 8);
}

void bigint_math_bigint_mul::thread_tmp_31_fu_320_p2() {
    tmp_31_fu_320_p2 = (!ap_const_lv9_FF.is_01() || !j_reg_189.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_FF) - sc_biguint<9>(j_reg_189.read()));
}

void bigint_math_bigint_mul::thread_tmp_32_fu_326_p1() {
    tmp_32_fu_326_p1 = esl_zext<64,9>(tmp_31_fu_320_p2.read());
}

void bigint_math_bigint_mul::thread_tmp_33_cast_fu_336_p0() {
    tmp_33_cast_fu_336_p0 = tempA_q0.read();
}

void bigint_math_bigint_mul::thread_tmp_34_fu_340_p0() {
    tmp_34_fu_340_p0 =  (sc_lv<8>) (tmp_cast_reg_514.read());
}

void bigint_math_bigint_mul::thread_tmp_34_fu_340_p1() {
    tmp_34_fu_340_p1 =  (sc_lv<8>) (tmp_34_fu_340_p10.read());
}

void bigint_math_bigint_mul::thread_tmp_34_fu_340_p10() {
    tmp_34_fu_340_p10 = esl_zext<16,8>(tmp_33_cast_fu_336_p0.read());
}

void bigint_math_bigint_mul::thread_tmp_34_fu_340_p2() {
    tmp_34_fu_340_p2 = (!tmp_34_fu_340_p0.read().is_01() || !tmp_34_fu_340_p1.read().is_01())? sc_lv<16>(): sc_biguint<8>(tmp_34_fu_340_p0.read()) * sc_biguint<8>(tmp_34_fu_340_p1.read());
}

void bigint_math_bigint_mul::thread_tmp_36_fu_355_p2() {
    tmp_36_fu_355_p2 = (carry_fu_345_p4.read() | prod_fu_331_p2.read());
}

void bigint_math_bigint_mul::thread_tmp_37_fu_361_p2() {
    tmp_37_fu_361_p2 = (!tmp_36_fu_355_p2.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_36_fu_355_p2.read() == ap_const_lv8_0);
}

void bigint_math_bigint_mul::thread_tmp_38_fu_367_p1() {
    tmp_38_fu_367_p1 = esl_sext<64,9>(k5_reg_200.read());
}

void bigint_math_bigint_mul::thread_tmp_39_cast_fu_372_p1() {
    tmp_39_cast_fu_372_p1 = esl_zext<9,8>(sum_q0.read());
}

void bigint_math_bigint_mul::thread_tmp_40_cast_fu_376_p1() {
    tmp_40_cast_fu_376_p1 = esl_zext<9,8>(prod_reg_532.read());
}

void bigint_math_bigint_mul::thread_tmp_40_fu_379_p2() {
    tmp_40_fu_379_p2 = (!tmp_39_cast_fu_372_p1.read().is_01() || !tmp_40_cast_fu_376_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_39_cast_fu_372_p1.read()) + sc_biguint<9>(tmp_40_cast_fu_376_p1.read()));
}

void bigint_math_bigint_mul::thread_tmp_41_fu_393_p2() {
    tmp_41_fu_393_p2 = (!ap_const_lv9_1FF.is_01() || !k5_reg_200.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1FF) + sc_biguint<9>(k5_reg_200.read()));
}

void bigint_math_bigint_mul::thread_tmp_42_fu_399_p1() {
    tmp_42_fu_399_p1 = esl_sext<64,9>(tmp_41_fu_393_p2.read());
}

void bigint_math_bigint_mul::thread_tmp_44_fu_404_p2() {
    tmp_44_fu_404_p2 = (!reg_243.read().is_01() || !prod_reg_532.read().is_01())? sc_lv<8>(): (sc_biguint<8>(reg_243.read()) + sc_biguint<8>(prod_reg_532.read()));
}

void bigint_math_bigint_mul::thread_tmp_46_fu_421_p2() {
    tmp_46_fu_421_p2 = (!tmp_51_cast_fu_414_p1.read().is_01() || !tmp_52_cast_fu_418_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_51_cast_fu_414_p1.read()) + sc_biguint<9>(tmp_52_cast_fu_418_p1.read()));
}

void bigint_math_bigint_mul::thread_tmp_47_fu_439_p2() {
    tmp_47_fu_439_p2 = (!ap_const_lv10_3FE.is_01() || !k5_cast_fu_435_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3FE) + sc_bigint<10>(k5_cast_fu_435_p1.read()));
}

void bigint_math_bigint_mul::thread_tmp_48_fu_445_p1() {
    tmp_48_fu_445_p1 = esl_sext<64,10>(tmp_47_fu_439_p2.read());
}

void bigint_math_bigint_mul::thread_tmp_50_fu_450_p2() {
    tmp_50_fu_450_p2 = (!reg_243.read().is_01() || !carry_reg_538.read().is_01())? sc_lv<8>(): (sc_biguint<8>(reg_243.read()) + sc_biguint<8>(carry_reg_538.read()));
}

void bigint_math_bigint_mul::thread_tmp_51_cast_fu_414_p1() {
    tmp_51_cast_fu_414_p1 = esl_zext<9,8>(sum_q0.read());
}

void bigint_math_bigint_mul::thread_tmp_52_cast_fu_418_p1() {
    tmp_52_cast_fu_418_p1 = esl_zext<9,8>(carry_reg_538.read());
}

void bigint_math_bigint_mul::thread_tmp_9_fu_385_p3() {
    tmp_9_fu_385_p3 = tmp_40_fu_379_p2.read().range(8, 8);
}

void bigint_math_bigint_mul::thread_tmp_cast_fu_304_p0() {
    tmp_cast_fu_304_p0 = tempB_q0.read();
}

void bigint_math_bigint_mul::thread_tmp_cast_fu_304_p1() {
    tmp_cast_fu_304_p1 = esl_zext<16,8>(tmp_cast_fu_304_p0.read());
}

void bigint_math_bigint_mul::thread_tmp_fu_299_p1() {
    tmp_fu_299_p1 = esl_zext<64,9>(k_fu_293_p2.read());
}

void bigint_math_bigint_mul::thread_tmp_i5_fu_276_p1() {
    tmp_i5_fu_276_p1 = esl_zext<64,9>(i_i3_reg_167.read());
}

void bigint_math_bigint_mul::thread_tmp_i_fu_259_p1() {
    tmp_i_fu_259_p1 = esl_zext<64,9>(i_i_reg_156.read());
}

void bigint_math_bigint_mul::thread_tmp_s_fu_409_p1() {
    tmp_s_fu_409_p1 = esl_sext<64,9>(grp_fu_237_p2.read());
}

void bigint_math_bigint_mul::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_217_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_223_ap_done.read()))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(exitcond_i_fu_247_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i4_fu_264_p2.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 64 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_217_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_223_ap_done.read()))) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_281_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_308_p2.read())) {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            }
            break;
        case 1024 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_37_fu_361_p2.read())) {
                ap_NS_fsm = ap_ST_st18_fsm_17;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 262144 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_add_1_fu_210_ap_done.read())) {
                ap_NS_fsm = ap_ST_st20_fsm_19;
            } else {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            }
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_217_ap_done.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st21_fsm_20;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

