// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "bigint_math_bigint_add.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic bigint_math_bigint_add::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic bigint_math_bigint_add::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> bigint_math_bigint_add::ap_ST_st1_fsm_0 = "1";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st2_fsm_1 = "10";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st3_fsm_2 = "100";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st4_fsm_3 = "1000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st5_fsm_4 = "10000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st6_fsm_5 = "100000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<15> bigint_math_bigint_add::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> bigint_math_bigint_add::ap_const_lv1_1 = "1";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_8 = "1000";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_C = "1100";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_2 = "10";
const sc_lv<1> bigint_math_bigint_add::ap_const_lv1_0 = "0";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_4 = "100";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_7 = "111";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_9 = "1001";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_B = "1011";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_D = "1101";
const sc_lv<9> bigint_math_bigint_add::ap_const_lv9_0 = "000000000";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_1 = "1";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_3 = "11";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_5 = "101";
const sc_lv<9> bigint_math_bigint_add::ap_const_lv9_FF = "11111111";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_6 = "110";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_E = "1110";
const sc_lv<32> bigint_math_bigint_add::ap_const_lv32_A = "1010";
const sc_lv<8> bigint_math_bigint_add::ap_const_lv8_1 = "1";
const sc_lv<9> bigint_math_bigint_add::ap_const_lv9_100 = "100000000";
const sc_lv<9> bigint_math_bigint_add::ap_const_lv9_1 = "1";
const sc_lv<9> bigint_math_bigint_add::ap_const_lv9_1FF = "111111111";
const sc_lv<9> bigint_math_bigint_add::ap_const_lv9_1FE = "111111110";

bigint_math_bigint_add::bigint_math_bigint_add(sc_module_name name) : sc_module(name), mVcdFile(0) {
    tempA_U = new bigint_math_bigint_add_tempA("tempA_U");
    tempA_U->clk(ap_clk);
    tempA_U->reset(ap_rst);
    tempA_U->address0(tempA_address0);
    tempA_U->ce0(tempA_ce0);
    tempA_U->we0(tempA_we0);
    tempA_U->d0(tempA_d0);
    tempA_U->q0(tempA_q0);
    tempB_U = new bigint_math_bigint_add_tempA("tempB_U");
    tempB_U->clk(ap_clk);
    tempB_U->reset(ap_rst);
    tempB_U->address0(tempB_address0);
    tempB_U->ce0(tempB_ce0);
    tempB_U->we0(tempB_we0);
    tempB_U->d0(tempB_d0);
    tempB_U->q0(tempB_q0);
    grp_bigint_math_bigint_zero_fu_182 = new bigint_math_bigint_zero("grp_bigint_math_bigint_zero_fu_182");
    grp_bigint_math_bigint_zero_fu_182->ap_clk(ap_clk);
    grp_bigint_math_bigint_zero_fu_182->ap_rst(ap_rst);
    grp_bigint_math_bigint_zero_fu_182->ap_start(grp_bigint_math_bigint_zero_fu_182_ap_start);
    grp_bigint_math_bigint_zero_fu_182->ap_done(grp_bigint_math_bigint_zero_fu_182_ap_done);
    grp_bigint_math_bigint_zero_fu_182->ap_idle(grp_bigint_math_bigint_zero_fu_182_ap_idle);
    grp_bigint_math_bigint_zero_fu_182->ap_ready(grp_bigint_math_bigint_zero_fu_182_ap_ready);
    grp_bigint_math_bigint_zero_fu_182->in_r_address0(grp_bigint_math_bigint_zero_fu_182_in_r_address0);
    grp_bigint_math_bigint_zero_fu_182->in_r_ce0(grp_bigint_math_bigint_zero_fu_182_in_r_ce0);
    grp_bigint_math_bigint_zero_fu_182->in_r_we0(grp_bigint_math_bigint_zero_fu_182_in_r_we0);
    grp_bigint_math_bigint_zero_fu_182->in_r_d0(grp_bigint_math_bigint_zero_fu_182_in_r_d0);
    grp_bigint_math_bigint_zero_fu_188 = new bigint_math_bigint_zero("grp_bigint_math_bigint_zero_fu_188");
    grp_bigint_math_bigint_zero_fu_188->ap_clk(ap_clk);
    grp_bigint_math_bigint_zero_fu_188->ap_rst(ap_rst);
    grp_bigint_math_bigint_zero_fu_188->ap_start(grp_bigint_math_bigint_zero_fu_188_ap_start);
    grp_bigint_math_bigint_zero_fu_188->ap_done(grp_bigint_math_bigint_zero_fu_188_ap_done);
    grp_bigint_math_bigint_zero_fu_188->ap_idle(grp_bigint_math_bigint_zero_fu_188_ap_idle);
    grp_bigint_math_bigint_zero_fu_188->ap_ready(grp_bigint_math_bigint_zero_fu_188_ap_ready);
    grp_bigint_math_bigint_zero_fu_188->in_r_address0(grp_bigint_math_bigint_zero_fu_188_in_r_address0);
    grp_bigint_math_bigint_zero_fu_188->in_r_ce0(grp_bigint_math_bigint_zero_fu_188_in_r_ce0);
    grp_bigint_math_bigint_zero_fu_188->in_r_we0(grp_bigint_math_bigint_zero_fu_188_in_r_we0);
    grp_bigint_math_bigint_zero_fu_188->in_r_d0(grp_bigint_math_bigint_zero_fu_188_in_r_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_i_fu_218_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_fu_244_p3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_fu_244_p3 );

    SC_METHOD(thread_ap_sig_110);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_139);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_148);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_166);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_212);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_224);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_233);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_245);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_254);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_286);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_60);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_67);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_77);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_94);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_139 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_286 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_148 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_67 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_166 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_254 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_32 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_212 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_77 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_224 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_94 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_233 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_245 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_110 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_60 );

    SC_METHOD(thread_b_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_i1_fu_235_p1 );

    SC_METHOD(thread_b_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_carry_fu_287_p1);
    sensitive << ( tmp_25_fu_279_p3 );

    SC_METHOD(thread_exitcond_i1_fu_223_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( i_i1_reg_159 );

    SC_METHOD(thread_exitcond_i_fu_206_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( i_i_reg_148 );

    SC_METHOD(thread_grp_bigint_math_bigint_zero_fu_182_ap_start);
    sensitive << ( ap_reg_grp_bigint_math_bigint_zero_fu_182_ap_start );

    SC_METHOD(thread_grp_bigint_math_bigint_zero_fu_188_ap_start);
    sensitive << ( ap_reg_grp_bigint_math_bigint_zero_fu_188_ap_start );

    SC_METHOD(thread_grp_fu_195_p2);
    sensitive << ( out_r_q0 );

    SC_METHOD(thread_i_15_fu_212_p2);
    sensitive << ( i_i_reg_148 );

    SC_METHOD(thread_i_16_fu_329_p2);
    sensitive << ( i_reg_170 );

    SC_METHOD(thread_i_4_fu_229_p2);
    sensitive << ( i_i1_reg_159 );

    SC_METHOD(thread_i_cast_fu_240_p1);
    sensitive << ( i_reg_170 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( out_addr_reg_426 );
    sensitive << ( out_addr_3_reg_450 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( out_addr_4_reg_465 );
    sensitive << ( out_addr_5_reg_474 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_in_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( tmp_s_fu_252_p1 );
    sensitive << ( tmp_108_fu_319_p1 );
    sensitive << ( tmp_111_fu_335_p1 );
    sensitive << ( tmp_114_fu_367_p1 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_in_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( tmp_110_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_116_reg_479 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_in_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( grp_fu_195_p2 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( tmp_26_reg_446 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_27_reg_470 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_in_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_sum_fu_259_p2);
    sensitive << ( tempA_q0 );
    sensitive << ( tempB_q0 );

    SC_METHOD(thread_tempA_address0);
    sensitive << ( tmp_i_reg_385 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_in_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_s_fu_252_p1 );

    SC_METHOD(thread_tempA_ce0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_in_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tempA_d0);
    sensitive << ( a_q0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_in_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tempA_we0);
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_in_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tempB_address0);
    sensitive << ( tmp_i1_reg_403 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_188_in_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_s_fu_252_p1 );

    SC_METHOD(thread_tempB_ce0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_188_in_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tempB_d0);
    sensitive << ( b_q0 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_188_in_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tempB_we0);
    sensitive << ( grp_bigint_math_bigint_zero_fu_188_in_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tmp_105_fu_273_p2);
    sensitive << ( tmp_118_cast_fu_265_p1 );
    sensitive << ( tmp_119_cast_fu_269_p1 );

    SC_METHOD(thread_tmp_106_fu_299_p2);
    sensitive << ( tmp_123_cast_fu_295_p1 );
    sensitive << ( tmp_122_cast_fu_291_p1 );

    SC_METHOD(thread_tmp_107_fu_313_p2);
    sensitive << ( i_reg_170 );

    SC_METHOD(thread_tmp_108_fu_319_p1);
    sensitive << ( tmp_107_fu_313_p2 );

    SC_METHOD(thread_tmp_110_fu_324_p2);
    sensitive << ( reg_202 );
    sensitive << ( sum_reg_431 );

    SC_METHOD(thread_tmp_111_fu_335_p1);
    sensitive << ( i_16_fu_329_p2 );

    SC_METHOD(thread_tmp_112_fu_347_p2);
    sensitive << ( tmp_134_cast_fu_344_p1 );
    sensitive << ( tmp_133_cast_fu_340_p1 );

    SC_METHOD(thread_tmp_113_fu_361_p2);
    sensitive << ( i_reg_170 );

    SC_METHOD(thread_tmp_114_fu_367_p1);
    sensitive << ( tmp_113_fu_361_p2 );

    SC_METHOD(thread_tmp_116_fu_372_p2);
    sensitive << ( reg_202 );
    sensitive << ( carry_reg_441 );

    SC_METHOD(thread_tmp_118_cast_fu_265_p1);
    sensitive << ( tempA_q0 );

    SC_METHOD(thread_tmp_119_cast_fu_269_p1);
    sensitive << ( tempB_q0 );

    SC_METHOD(thread_tmp_122_cast_fu_291_p1);
    sensitive << ( out_r_q0 );

    SC_METHOD(thread_tmp_123_cast_fu_295_p1);
    sensitive << ( sum_fu_259_p2 );

    SC_METHOD(thread_tmp_133_cast_fu_340_p1);
    sensitive << ( out_r_q0 );

    SC_METHOD(thread_tmp_134_cast_fu_344_p1);
    sensitive << ( tmp_25_reg_436 );

    SC_METHOD(thread_tmp_25_fu_279_p3);
    sensitive << ( tmp_105_fu_273_p2 );

    SC_METHOD(thread_tmp_26_fu_305_p3);
    sensitive << ( tmp_106_fu_299_p2 );

    SC_METHOD(thread_tmp_27_fu_353_p3);
    sensitive << ( tmp_112_fu_347_p2 );

    SC_METHOD(thread_tmp_fu_244_p3);
    sensitive << ( i_reg_170 );

    SC_METHOD(thread_tmp_i1_fu_235_p1);
    sensitive << ( i_i1_reg_159 );

    SC_METHOD(thread_tmp_i_fu_218_p1);
    sensitive << ( i_i_reg_148 );

    SC_METHOD(thread_tmp_s_fu_252_p1);
    sensitive << ( i_cast_fu_240_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_i_fu_206_p2 );
    sensitive << ( exitcond_i1_fu_223_p2 );
    sensitive << ( tmp_fu_244_p3 );
    sensitive << ( grp_bigint_math_bigint_zero_fu_182_ap_done );
    sensitive << ( grp_bigint_math_bigint_zero_fu_188_ap_done );

    ap_CS_fsm = "000000000000001";
    ap_reg_grp_bigint_math_bigint_zero_fu_182_ap_start = SC_LOGIC_0;
    ap_reg_grp_bigint_math_bigint_zero_fu_188_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "bigint_math_bigint_add_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
    sc_trace(mVcdFile, out_r_q0, "(port)out_r_q0");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, b_address0, "(port)b_address0");
    sc_trace(mVcdFile, b_ce0, "(port)b_ce0");
    sc_trace(mVcdFile, b_q0, "(port)b_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_32, "ap_sig_32");
    sc_trace(mVcdFile, reg_202, "reg_202");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_60, "ap_sig_60");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_67, "ap_sig_67");
    sc_trace(mVcdFile, i_15_fu_212_p2, "i_15_fu_212_p2");
    sc_trace(mVcdFile, i_15_reg_380, "i_15_reg_380");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_77, "ap_sig_77");
    sc_trace(mVcdFile, tmp_i_fu_218_p1, "tmp_i_fu_218_p1");
    sc_trace(mVcdFile, tmp_i_reg_385, "tmp_i_reg_385");
    sc_trace(mVcdFile, exitcond_i_fu_206_p2, "exitcond_i_fu_206_p2");
    sc_trace(mVcdFile, i_4_fu_229_p2, "i_4_fu_229_p2");
    sc_trace(mVcdFile, i_4_reg_398, "i_4_reg_398");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_94, "ap_sig_94");
    sc_trace(mVcdFile, tmp_i1_fu_235_p1, "tmp_i1_fu_235_p1");
    sc_trace(mVcdFile, tmp_i1_reg_403, "tmp_i1_reg_403");
    sc_trace(mVcdFile, exitcond_i1_fu_223_p2, "exitcond_i1_fu_223_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_110, "ap_sig_110");
    sc_trace(mVcdFile, tmp_fu_244_p3, "tmp_fu_244_p3");
    sc_trace(mVcdFile, out_addr_reg_426, "out_addr_reg_426");
    sc_trace(mVcdFile, sum_fu_259_p2, "sum_fu_259_p2");
    sc_trace(mVcdFile, sum_reg_431, "sum_reg_431");
    sc_trace(mVcdFile, tmp_25_fu_279_p3, "tmp_25_fu_279_p3");
    sc_trace(mVcdFile, tmp_25_reg_436, "tmp_25_reg_436");
    sc_trace(mVcdFile, carry_fu_287_p1, "carry_fu_287_p1");
    sc_trace(mVcdFile, carry_reg_441, "carry_reg_441");
    sc_trace(mVcdFile, tmp_26_fu_305_p3, "tmp_26_fu_305_p3");
    sc_trace(mVcdFile, tmp_26_reg_446, "tmp_26_reg_446");
    sc_trace(mVcdFile, out_addr_3_reg_450, "out_addr_3_reg_450");
    sc_trace(mVcdFile, tmp_110_fu_324_p2, "tmp_110_fu_324_p2");
    sc_trace(mVcdFile, tmp_110_reg_455, "tmp_110_reg_455");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_139, "ap_sig_139");
    sc_trace(mVcdFile, i_16_fu_329_p2, "i_16_fu_329_p2");
    sc_trace(mVcdFile, i_16_reg_460, "i_16_reg_460");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_148, "ap_sig_148");
    sc_trace(mVcdFile, out_addr_4_reg_465, "out_addr_4_reg_465");
    sc_trace(mVcdFile, tmp_27_fu_353_p3, "tmp_27_fu_353_p3");
    sc_trace(mVcdFile, tmp_27_reg_470, "tmp_27_reg_470");
    sc_trace(mVcdFile, out_addr_5_reg_474, "out_addr_5_reg_474");
    sc_trace(mVcdFile, tmp_116_fu_372_p2, "tmp_116_fu_372_p2");
    sc_trace(mVcdFile, tmp_116_reg_479, "tmp_116_reg_479");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_166, "ap_sig_166");
    sc_trace(mVcdFile, tempA_address0, "tempA_address0");
    sc_trace(mVcdFile, tempA_ce0, "tempA_ce0");
    sc_trace(mVcdFile, tempA_we0, "tempA_we0");
    sc_trace(mVcdFile, tempA_d0, "tempA_d0");
    sc_trace(mVcdFile, tempA_q0, "tempA_q0");
    sc_trace(mVcdFile, tempB_address0, "tempB_address0");
    sc_trace(mVcdFile, tempB_ce0, "tempB_ce0");
    sc_trace(mVcdFile, tempB_we0, "tempB_we0");
    sc_trace(mVcdFile, tempB_d0, "tempB_d0");
    sc_trace(mVcdFile, tempB_q0, "tempB_q0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_182_ap_start, "grp_bigint_math_bigint_zero_fu_182_ap_start");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_182_ap_done, "grp_bigint_math_bigint_zero_fu_182_ap_done");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_182_ap_idle, "grp_bigint_math_bigint_zero_fu_182_ap_idle");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_182_ap_ready, "grp_bigint_math_bigint_zero_fu_182_ap_ready");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_182_in_r_address0, "grp_bigint_math_bigint_zero_fu_182_in_r_address0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_182_in_r_ce0, "grp_bigint_math_bigint_zero_fu_182_in_r_ce0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_182_in_r_we0, "grp_bigint_math_bigint_zero_fu_182_in_r_we0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_182_in_r_d0, "grp_bigint_math_bigint_zero_fu_182_in_r_d0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_188_ap_start, "grp_bigint_math_bigint_zero_fu_188_ap_start");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_188_ap_done, "grp_bigint_math_bigint_zero_fu_188_ap_done");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_188_ap_idle, "grp_bigint_math_bigint_zero_fu_188_ap_idle");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_188_ap_ready, "grp_bigint_math_bigint_zero_fu_188_ap_ready");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_188_in_r_address0, "grp_bigint_math_bigint_zero_fu_188_in_r_address0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_188_in_r_ce0, "grp_bigint_math_bigint_zero_fu_188_in_r_ce0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_188_in_r_we0, "grp_bigint_math_bigint_zero_fu_188_in_r_we0");
    sc_trace(mVcdFile, grp_bigint_math_bigint_zero_fu_188_in_r_d0, "grp_bigint_math_bigint_zero_fu_188_in_r_d0");
    sc_trace(mVcdFile, i_i_reg_148, "i_i_reg_148");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_212, "ap_sig_212");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_224, "ap_sig_224");
    sc_trace(mVcdFile, i_i1_reg_159, "i_i1_reg_159");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_233, "ap_sig_233");
    sc_trace(mVcdFile, i_reg_170, "i_reg_170");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_245, "ap_sig_245");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_254, "ap_sig_254");
    sc_trace(mVcdFile, ap_reg_grp_bigint_math_bigint_zero_fu_182_ap_start, "ap_reg_grp_bigint_math_bigint_zero_fu_182_ap_start");
    sc_trace(mVcdFile, ap_reg_grp_bigint_math_bigint_zero_fu_188_ap_start, "ap_reg_grp_bigint_math_bigint_zero_fu_188_ap_start");
    sc_trace(mVcdFile, tmp_s_fu_252_p1, "tmp_s_fu_252_p1");
    sc_trace(mVcdFile, tmp_108_fu_319_p1, "tmp_108_fu_319_p1");
    sc_trace(mVcdFile, tmp_111_fu_335_p1, "tmp_111_fu_335_p1");
    sc_trace(mVcdFile, tmp_114_fu_367_p1, "tmp_114_fu_367_p1");
    sc_trace(mVcdFile, grp_fu_195_p2, "grp_fu_195_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_286, "ap_sig_286");
    sc_trace(mVcdFile, i_cast_fu_240_p1, "i_cast_fu_240_p1");
    sc_trace(mVcdFile, tmp_118_cast_fu_265_p1, "tmp_118_cast_fu_265_p1");
    sc_trace(mVcdFile, tmp_119_cast_fu_269_p1, "tmp_119_cast_fu_269_p1");
    sc_trace(mVcdFile, tmp_105_fu_273_p2, "tmp_105_fu_273_p2");
    sc_trace(mVcdFile, tmp_123_cast_fu_295_p1, "tmp_123_cast_fu_295_p1");
    sc_trace(mVcdFile, tmp_122_cast_fu_291_p1, "tmp_122_cast_fu_291_p1");
    sc_trace(mVcdFile, tmp_106_fu_299_p2, "tmp_106_fu_299_p2");
    sc_trace(mVcdFile, tmp_107_fu_313_p2, "tmp_107_fu_313_p2");
    sc_trace(mVcdFile, tmp_134_cast_fu_344_p1, "tmp_134_cast_fu_344_p1");
    sc_trace(mVcdFile, tmp_133_cast_fu_340_p1, "tmp_133_cast_fu_340_p1");
    sc_trace(mVcdFile, tmp_112_fu_347_p2, "tmp_112_fu_347_p2");
    sc_trace(mVcdFile, tmp_113_fu_361_p2, "tmp_113_fu_361_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

bigint_math_bigint_add::~bigint_math_bigint_add() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete tempA_U;
    delete tempB_U;
    delete grp_bigint_math_bigint_zero_fu_182;
    delete grp_bigint_math_bigint_zero_fu_188;
}

void bigint_math_bigint_add::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_bigint_math_bigint_zero_fu_182_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
              !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
              !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i1_fu_223_p2.read())))) {
            ap_reg_grp_bigint_math_bigint_zero_fu_182_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_bigint_math_bigint_zero_fu_182_ap_ready.read())) {
            ap_reg_grp_bigint_math_bigint_zero_fu_182_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_bigint_math_bigint_zero_fu_188_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_grp_bigint_math_bigint_zero_fu_188_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_bigint_math_bigint_zero_fu_188_ap_ready.read())) {
            ap_reg_grp_bigint_math_bigint_zero_fu_188_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(exitcond_i_fu_206_p2.read(), ap_const_lv1_0))) {
        i_i1_reg_159 = ap_const_lv9_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        i_i1_reg_159 = i_4_reg_398.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_i_reg_148 = i_15_reg_380.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_182_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_188_ap_done.read())))) {
        i_i_reg_148 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        i_reg_170 = i_16_reg_460.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_182_ap_done.read()))) {
        i_reg_170 = ap_const_lv9_FF;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        carry_reg_441 = carry_fu_287_p1.read();
        sum_reg_431 = sum_fu_259_p2.read();
        tmp_25_reg_436 = tmp_105_fu_273_p2.read().range(8, 8);
        tmp_26_reg_446 = tmp_106_fu_299_p2.read().range(8, 8);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_15_reg_380 = i_15_fu_212_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        i_16_reg_460 = i_16_fu_329_p2.read();
        out_addr_4_reg_465 =  (sc_lv<8>) (tmp_111_fu_335_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        i_4_reg_398 = i_4_fu_229_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_fu_305_p3.read()))) {
        out_addr_3_reg_450 =  (sc_lv<8>) (tmp_108_fu_319_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_fu_353_p3.read()))) {
        out_addr_5_reg_474 =  (sc_lv<8>) (tmp_114_fu_367_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_244_p3.read()))) {
        out_addr_reg_426 =  (sc_lv<8>) (tmp_s_fu_252_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()))) {
        reg_202 = out_r_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        tmp_110_reg_455 = tmp_110_fu_324_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        tmp_116_reg_479 = tmp_116_fu_372_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        tmp_27_reg_470 = tmp_112_fu_347_p2.read().range(8, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i1_fu_223_p2.read()))) {
        tmp_i1_reg_403 = tmp_i1_fu_235_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_i_fu_206_p2.read(), ap_const_lv1_0))) {
        tmp_i_reg_385 = tmp_i_fu_218_p1.read();
    }
}

void bigint_math_bigint_add::thread_a_address0() {
    a_address0 =  (sc_lv<8>) (tmp_i_fu_218_p1.read());
}

void bigint_math_bigint_add::thread_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_244_p3.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_244_p3.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_110() {
    ap_sig_110 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void bigint_math_bigint_add::thread_ap_sig_139() {
    ap_sig_139 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void bigint_math_bigint_add::thread_ap_sig_148() {
    ap_sig_148 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void bigint_math_bigint_add::thread_ap_sig_166() {
    ap_sig_166 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void bigint_math_bigint_add::thread_ap_sig_212() {
    ap_sig_212 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void bigint_math_bigint_add::thread_ap_sig_224() {
    ap_sig_224 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void bigint_math_bigint_add::thread_ap_sig_233() {
    ap_sig_233 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void bigint_math_bigint_add::thread_ap_sig_245() {
    ap_sig_245 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void bigint_math_bigint_add::thread_ap_sig_254() {
    ap_sig_254 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void bigint_math_bigint_add::thread_ap_sig_286() {
    ap_sig_286 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void bigint_math_bigint_add::thread_ap_sig_32() {
    ap_sig_32 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void bigint_math_bigint_add::thread_ap_sig_60() {
    ap_sig_60 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void bigint_math_bigint_add::thread_ap_sig_67() {
    ap_sig_67 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void bigint_math_bigint_add::thread_ap_sig_77() {
    ap_sig_77 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void bigint_math_bigint_add::thread_ap_sig_94() {
    ap_sig_94 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_139.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_286.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_148.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_67.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_166.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_254.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_32.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_212.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_77.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_224.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_94.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_233.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_245.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_110.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_60.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_b_address0() {
    b_address0 =  (sc_lv<8>) (tmp_i1_fu_235_p1.read());
}

void bigint_math_bigint_add::thread_b_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        b_ce0 = ap_const_logic_1;
    } else {
        b_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_carry_fu_287_p1() {
    carry_fu_287_p1 = esl_zext<8,1>(tmp_25_fu_279_p3.read());
}

void bigint_math_bigint_add::thread_exitcond_i1_fu_223_p2() {
    exitcond_i1_fu_223_p2 = (!i_i1_reg_159.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_i1_reg_159.read() == ap_const_lv9_100);
}

void bigint_math_bigint_add::thread_exitcond_i_fu_206_p2() {
    exitcond_i_fu_206_p2 = (!i_i_reg_148.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_148.read() == ap_const_lv9_100);
}

void bigint_math_bigint_add::thread_grp_bigint_math_bigint_zero_fu_182_ap_start() {
    grp_bigint_math_bigint_zero_fu_182_ap_start = ap_reg_grp_bigint_math_bigint_zero_fu_182_ap_start.read();
}

void bigint_math_bigint_add::thread_grp_bigint_math_bigint_zero_fu_188_ap_start() {
    grp_bigint_math_bigint_zero_fu_188_ap_start = ap_reg_grp_bigint_math_bigint_zero_fu_188_ap_start.read();
}

void bigint_math_bigint_add::thread_grp_fu_195_p2() {
    grp_fu_195_p2 = (!ap_const_lv8_1.is_01() || !out_r_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(out_r_q0.read()));
}

void bigint_math_bigint_add::thread_i_15_fu_212_p2() {
    i_15_fu_212_p2 = (!i_i_reg_148.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_i_reg_148.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void bigint_math_bigint_add::thread_i_16_fu_329_p2() {
    i_16_fu_329_p2 = (!i_reg_170.read().is_01() || !ap_const_lv9_1FF.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_170.read()) + sc_bigint<9>(ap_const_lv9_1FF));
}

void bigint_math_bigint_add::thread_i_4_fu_229_p2() {
    i_4_fu_229_p2 = (!i_i1_reg_159.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_i1_reg_159.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void bigint_math_bigint_add::thread_i_cast_fu_240_p1() {
    i_cast_fu_240_p1 = esl_sext<32,9>(i_reg_170.read());
}

void bigint_math_bigint_add::thread_out_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        out_r_address0 = out_addr_4_reg_465.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        out_r_address0 = out_addr_5_reg_474.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        out_r_address0 = out_addr_reg_426.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        out_r_address0 = out_addr_3_reg_450.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        out_r_address0 =  (sc_lv<8>) (tmp_114_fu_367_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        out_r_address0 =  (sc_lv<8>) (tmp_111_fu_335_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        out_r_address0 =  (sc_lv<8>) (tmp_108_fu_319_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        out_r_address0 =  (sc_lv<8>) (tmp_s_fu_252_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        out_r_address0 = grp_bigint_math_bigint_zero_fu_182_in_r_address0.read();
    } else {
        out_r_address0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_add::thread_out_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        out_r_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        out_r_ce0 = grp_bigint_math_bigint_zero_fu_182_in_r_ce0.read();
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_out_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        out_r_d0 = tmp_116_reg_479.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        out_r_d0 = tmp_110_reg_455.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        out_r_d0 = grp_fu_195_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        out_r_d0 = grp_bigint_math_bigint_zero_fu_182_in_r_d0.read();
    } else {
        out_r_d0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_add::thread_out_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_446.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_470.read())))) {
        out_r_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        out_r_we0 = grp_bigint_math_bigint_zero_fu_182_in_r_we0.read();
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_sum_fu_259_p2() {
    sum_fu_259_p2 = (!tempA_q0.read().is_01() || !tempB_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tempA_q0.read()) + sc_biguint<8>(tempB_q0.read()));
}

void bigint_math_bigint_add::thread_tempA_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        tempA_address0 =  (sc_lv<8>) (tmp_i_reg_385.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        tempA_address0 =  (sc_lv<8>) (tmp_s_fu_252_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempA_address0 = grp_bigint_math_bigint_zero_fu_182_in_r_address0.read();
    } else {
        tempA_address0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_add::thread_tempA_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        tempA_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempA_ce0 = grp_bigint_math_bigint_zero_fu_182_in_r_ce0.read();
    } else {
        tempA_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_tempA_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        tempA_d0 = a_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempA_d0 = grp_bigint_math_bigint_zero_fu_182_in_r_d0.read();
    } else {
        tempA_d0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_add::thread_tempA_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        tempA_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempA_we0 = grp_bigint_math_bigint_zero_fu_182_in_r_we0.read();
    } else {
        tempA_we0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_tempB_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        tempB_address0 =  (sc_lv<8>) (tmp_i1_reg_403.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        tempB_address0 =  (sc_lv<8>) (tmp_s_fu_252_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempB_address0 = grp_bigint_math_bigint_zero_fu_188_in_r_address0.read();
    } else {
        tempB_address0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_add::thread_tempB_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        tempB_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempB_ce0 = grp_bigint_math_bigint_zero_fu_188_in_r_ce0.read();
    } else {
        tempB_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_tempB_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        tempB_d0 = b_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempB_d0 = grp_bigint_math_bigint_zero_fu_188_in_r_d0.read();
    } else {
        tempB_d0 = "XXXXXXXX";
    }
}

void bigint_math_bigint_add::thread_tempB_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        tempB_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tempB_we0 = grp_bigint_math_bigint_zero_fu_188_in_r_we0.read();
    } else {
        tempB_we0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_add::thread_tmp_105_fu_273_p2() {
    tmp_105_fu_273_p2 = (!tmp_118_cast_fu_265_p1.read().is_01() || !tmp_119_cast_fu_269_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_118_cast_fu_265_p1.read()) + sc_biguint<9>(tmp_119_cast_fu_269_p1.read()));
}

void bigint_math_bigint_add::thread_tmp_106_fu_299_p2() {
    tmp_106_fu_299_p2 = (!tmp_123_cast_fu_295_p1.read().is_01() || !tmp_122_cast_fu_291_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_123_cast_fu_295_p1.read()) + sc_biguint<9>(tmp_122_cast_fu_291_p1.read()));
}

void bigint_math_bigint_add::thread_tmp_107_fu_313_p2() {
    tmp_107_fu_313_p2 = (!ap_const_lv9_1FF.is_01() || !i_reg_170.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1FF) + sc_biguint<9>(i_reg_170.read()));
}

void bigint_math_bigint_add::thread_tmp_108_fu_319_p1() {
    tmp_108_fu_319_p1 = esl_sext<64,9>(tmp_107_fu_313_p2.read());
}

void bigint_math_bigint_add::thread_tmp_110_fu_324_p2() {
    tmp_110_fu_324_p2 = (!sum_reg_431.read().is_01() || !reg_202.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sum_reg_431.read()) + sc_biguint<8>(reg_202.read()));
}

void bigint_math_bigint_add::thread_tmp_111_fu_335_p1() {
    tmp_111_fu_335_p1 = esl_sext<64,9>(i_16_fu_329_p2.read());
}

void bigint_math_bigint_add::thread_tmp_112_fu_347_p2() {
    tmp_112_fu_347_p2 = (!tmp_134_cast_fu_344_p1.read().is_01() || !tmp_133_cast_fu_340_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_134_cast_fu_344_p1.read()) + sc_biguint<9>(tmp_133_cast_fu_340_p1.read()));
}

void bigint_math_bigint_add::thread_tmp_113_fu_361_p2() {
    tmp_113_fu_361_p2 = (!ap_const_lv9_1FE.is_01() || !i_reg_170.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1FE) + sc_biguint<9>(i_reg_170.read()));
}

void bigint_math_bigint_add::thread_tmp_114_fu_367_p1() {
    tmp_114_fu_367_p1 = esl_sext<64,9>(tmp_113_fu_361_p2.read());
}

void bigint_math_bigint_add::thread_tmp_116_fu_372_p2() {
    tmp_116_fu_372_p2 = (!reg_202.read().is_01() || !carry_reg_441.read().is_01())? sc_lv<8>(): (sc_biguint<8>(reg_202.read()) + sc_biguint<8>(carry_reg_441.read()));
}

void bigint_math_bigint_add::thread_tmp_118_cast_fu_265_p1() {
    tmp_118_cast_fu_265_p1 = esl_zext<9,8>(tempA_q0.read());
}

void bigint_math_bigint_add::thread_tmp_119_cast_fu_269_p1() {
    tmp_119_cast_fu_269_p1 = esl_zext<9,8>(tempB_q0.read());
}

void bigint_math_bigint_add::thread_tmp_122_cast_fu_291_p1() {
    tmp_122_cast_fu_291_p1 = esl_zext<9,8>(out_r_q0.read());
}

void bigint_math_bigint_add::thread_tmp_123_cast_fu_295_p1() {
    tmp_123_cast_fu_295_p1 = esl_zext<9,8>(sum_fu_259_p2.read());
}

void bigint_math_bigint_add::thread_tmp_133_cast_fu_340_p1() {
    tmp_133_cast_fu_340_p1 = esl_zext<9,8>(out_r_q0.read());
}

void bigint_math_bigint_add::thread_tmp_134_cast_fu_344_p1() {
    tmp_134_cast_fu_344_p1 = esl_zext<9,1>(tmp_25_reg_436.read());
}

void bigint_math_bigint_add::thread_tmp_25_fu_279_p3() {
    tmp_25_fu_279_p3 = tmp_105_fu_273_p2.read().range(8, 8);
}

void bigint_math_bigint_add::thread_tmp_26_fu_305_p3() {
    tmp_26_fu_305_p3 = tmp_106_fu_299_p2.read().range(8, 8);
}

void bigint_math_bigint_add::thread_tmp_27_fu_353_p3() {
    tmp_27_fu_353_p3 = tmp_112_fu_347_p2.read().range(8, 8);
}

void bigint_math_bigint_add::thread_tmp_fu_244_p3() {
    tmp_fu_244_p3 = i_reg_170.read().range(8, 8);
}

void bigint_math_bigint_add::thread_tmp_i1_fu_235_p1() {
    tmp_i1_fu_235_p1 = esl_zext<64,9>(i_i1_reg_159.read());
}

void bigint_math_bigint_add::thread_tmp_i_fu_218_p1() {
    tmp_i_fu_218_p1 = esl_zext<64,9>(i_i_reg_148.read());
}

void bigint_math_bigint_add::thread_tmp_s_fu_252_p1() {
    tmp_s_fu_252_p1 = esl_zext<64,32>(i_cast_fu_240_p1.read());
}

void bigint_math_bigint_add::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_182_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_188_ap_done.read()))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(exitcond_i_fu_206_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i1_fu_223_p2.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_bigint_math_bigint_zero_fu_182_ap_done.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_244_p3.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

}

