// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "bigint_math_bigint_rightshift.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic bigint_math_bigint_rightshift::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic bigint_math_bigint_rightshift::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> bigint_math_bigint_rightshift::ap_ST_st1_fsm_0 = "1";
const sc_lv<6> bigint_math_bigint_rightshift::ap_ST_st2_fsm_1 = "10";
const sc_lv<6> bigint_math_bigint_rightshift::ap_ST_st3_fsm_2 = "100";
const sc_lv<6> bigint_math_bigint_rightshift::ap_ST_st4_fsm_3 = "1000";
const sc_lv<6> bigint_math_bigint_rightshift::ap_ST_st5_fsm_4 = "10000";
const sc_lv<6> bigint_math_bigint_rightshift::ap_ST_st6_fsm_5 = "100000";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> bigint_math_bigint_rightshift::ap_const_lv1_1 = "1";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_1 = "1";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_2 = "10";
const sc_lv<1> bigint_math_bigint_rightshift::ap_const_lv1_0 = "0";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_3 = "11";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_4 = "100";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_5 = "101";
const sc_lv<9> bigint_math_bigint_rightshift::ap_const_lv9_0 = "000000000";
const sc_lv<4> bigint_math_bigint_rightshift::ap_const_lv4_7 = "111";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_6 = "110";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_7 = "111";
const sc_lv<8> bigint_math_bigint_rightshift::ap_const_lv8_0 = "00000000";
const sc_lv<9> bigint_math_bigint_rightshift::ap_const_lv9_100 = "100000000";
const sc_lv<9> bigint_math_bigint_rightshift::ap_const_lv9_1 = "1";
const sc_lv<8> bigint_math_bigint_rightshift::ap_const_lv8_1 = "1";
const sc_lv<32> bigint_math_bigint_rightshift::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<8> bigint_math_bigint_rightshift::ap_const_lv8_7 = "111";
const sc_lv<4> bigint_math_bigint_rightshift::ap_const_lv4_F = "1111";

bigint_math_bigint_rightshift::bigint_math_bigint_rightshift(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( a_addr_reg_340 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( exitcond_fu_197_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( exitcond_fu_197_p2 );

    SC_METHOD(thread_ap_sig_107);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_71);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_86);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_47 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_56 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_71 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_86 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_107 );

    SC_METHOD(thread_b_fu_257_p2);
    sensitive << ( j_cast_reg_345 );
    sensitive << ( tmp_16_fu_251_p2 );

    SC_METHOD(thread_exitcond_fu_197_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( i_reg_99 );

    SC_METHOD(thread_exitcond_i_fu_180_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_i_reg_88 );

    SC_METHOD(thread_i_3_fu_203_p2);
    sensitive << ( i_reg_99 );

    SC_METHOD(thread_i_5_fu_186_p2);
    sensitive << ( i_i_reg_88 );

    SC_METHOD(thread_j_4_fu_318_p2);
    sensitive << ( j_reg_122 );

    SC_METHOD(thread_j_cast_fu_214_p1);
    sensitive << ( j_reg_122 );

    SC_METHOD(thread_k_2_phi_fu_161_p4);
    sensitive << ( tmp_17_reg_365 );
    sensitive << ( k_4_reg_374 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( k_1_reg_134 );

    SC_METHOD(thread_k_3_fu_232_p2);
    sensitive << ( k_1_reg_134 );

    SC_METHOD(thread_k_4_fu_273_p2);
    sensitive << ( k_1_reg_134 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_17_fu_262_p2 );
    sensitive << ( tmp_17_reg_365 );
    sensitive << ( out_addr_1_reg_369 );
    sensitive << ( out_addr_reg_379 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_i_fu_192_p1 );
    sensitive << ( tmp_21_fu_268_p1 );
    sensitive << ( tmp_18_fu_279_p1 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_17_fu_262_p2 );
    sensitive << ( tmp_17_reg_365 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_17_reg_365 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_22_fu_293_p2 );
    sensitive << ( tmp_19_fu_305_p2 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_17_reg_365 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( exitcond_i_fu_180_p2 );

    SC_METHOD(thread_outputBit_1_phi_fu_172_p4);
    sensitive << ( tmp_17_reg_365 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( outputBit_reg_145 );

    SC_METHOD(thread_outputBit_2_fu_312_p2);
    sensitive << ( outputBit_1_phi_fu_172_p4 );

    SC_METHOD(thread_p_k_1_fu_238_p3);
    sensitive << ( k_1_reg_134 );
    sensitive << ( tmp_s_fu_226_p2 );
    sensitive << ( k_3_fu_232_p2 );

    SC_METHOD(thread_tmp_15_fu_246_p2);
    sensitive << ( j_cast_reg_345 );

    SC_METHOD(thread_tmp_16_fu_251_p2);
    sensitive << ( a_q0 );
    sensitive << ( tmp_15_fu_246_p2 );

    SC_METHOD(thread_tmp_17_fu_262_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( outputBit_reg_145 );

    SC_METHOD(thread_tmp_18_fu_279_p1);
    sensitive << ( k_4_fu_273_p2 );

    SC_METHOD(thread_tmp_19_fu_305_p2);
    sensitive << ( out_r_q0 );
    sensitive << ( tmp_5_fu_300_p2 );

    SC_METHOD(thread_tmp_20_fu_288_p2);
    sensitive << ( b_reg_359 );
    sensitive << ( tmp_6_fu_284_p1 );

    SC_METHOD(thread_tmp_21_fu_268_p1);
    sensitive << ( k_1_reg_134 );

    SC_METHOD(thread_tmp_22_fu_293_p2);
    sensitive << ( out_r_q0 );
    sensitive << ( tmp_20_fu_288_p2 );

    SC_METHOD(thread_tmp_4_fu_218_p3);
    sensitive << ( j_reg_122 );

    SC_METHOD(thread_tmp_5_fu_300_p2);
    sensitive << ( b_reg_359 );

    SC_METHOD(thread_tmp_6_fu_284_p1);
    sensitive << ( outputBit_reg_145 );

    SC_METHOD(thread_tmp_fu_209_p1);
    sensitive << ( i_reg_99 );

    SC_METHOD(thread_tmp_i_fu_192_p1);
    sensitive << ( i_i_reg_88 );

    SC_METHOD(thread_tmp_s_fu_226_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_4_fu_218_p3 );
    sensitive << ( outputBit_reg_145 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_197_p2 );
    sensitive << ( tmp_4_fu_218_p3 );
    sensitive << ( exitcond_i_fu_180_p2 );

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "bigint_math_bigint_rightshift_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
    sc_trace(mVcdFile, out_r_q0, "(port)out_r_q0");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_23, "ap_sig_23");
    sc_trace(mVcdFile, i_5_fu_186_p2, "i_5_fu_186_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_47, "ap_sig_47");
    sc_trace(mVcdFile, i_3_fu_203_p2, "i_3_fu_203_p2");
    sc_trace(mVcdFile, i_3_reg_335, "i_3_reg_335");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_56, "ap_sig_56");
    sc_trace(mVcdFile, a_addr_reg_340, "a_addr_reg_340");
    sc_trace(mVcdFile, exitcond_fu_197_p2, "exitcond_fu_197_p2");
    sc_trace(mVcdFile, j_cast_fu_214_p1, "j_cast_fu_214_p1");
    sc_trace(mVcdFile, j_cast_reg_345, "j_cast_reg_345");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_71, "ap_sig_71");
    sc_trace(mVcdFile, p_k_1_fu_238_p3, "p_k_1_fu_238_p3");
    sc_trace(mVcdFile, tmp_4_fu_218_p3, "tmp_4_fu_218_p3");
    sc_trace(mVcdFile, b_fu_257_p2, "b_fu_257_p2");
    sc_trace(mVcdFile, b_reg_359, "b_reg_359");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_86, "ap_sig_86");
    sc_trace(mVcdFile, tmp_17_fu_262_p2, "tmp_17_fu_262_p2");
    sc_trace(mVcdFile, tmp_17_reg_365, "tmp_17_reg_365");
    sc_trace(mVcdFile, out_addr_1_reg_369, "out_addr_1_reg_369");
    sc_trace(mVcdFile, k_4_fu_273_p2, "k_4_fu_273_p2");
    sc_trace(mVcdFile, k_4_reg_374, "k_4_reg_374");
    sc_trace(mVcdFile, out_addr_reg_379, "out_addr_reg_379");
    sc_trace(mVcdFile, outputBit_2_fu_312_p2, "outputBit_2_fu_312_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_107, "ap_sig_107");
    sc_trace(mVcdFile, j_4_fu_318_p2, "j_4_fu_318_p2");
    sc_trace(mVcdFile, i_i_reg_88, "i_i_reg_88");
    sc_trace(mVcdFile, exitcond_i_fu_180_p2, "exitcond_i_fu_180_p2");
    sc_trace(mVcdFile, i_reg_99, "i_reg_99");
    sc_trace(mVcdFile, k_reg_110, "k_reg_110");
    sc_trace(mVcdFile, j_reg_122, "j_reg_122");
    sc_trace(mVcdFile, k_1_reg_134, "k_1_reg_134");
    sc_trace(mVcdFile, k_2_phi_fu_161_p4, "k_2_phi_fu_161_p4");
    sc_trace(mVcdFile, outputBit_reg_145, "outputBit_reg_145");
    sc_trace(mVcdFile, outputBit_1_phi_fu_172_p4, "outputBit_1_phi_fu_172_p4");
    sc_trace(mVcdFile, tmp_i_fu_192_p1, "tmp_i_fu_192_p1");
    sc_trace(mVcdFile, tmp_fu_209_p1, "tmp_fu_209_p1");
    sc_trace(mVcdFile, tmp_21_fu_268_p1, "tmp_21_fu_268_p1");
    sc_trace(mVcdFile, tmp_18_fu_279_p1, "tmp_18_fu_279_p1");
    sc_trace(mVcdFile, tmp_22_fu_293_p2, "tmp_22_fu_293_p2");
    sc_trace(mVcdFile, tmp_19_fu_305_p2, "tmp_19_fu_305_p2");
    sc_trace(mVcdFile, tmp_s_fu_226_p2, "tmp_s_fu_226_p2");
    sc_trace(mVcdFile, k_3_fu_232_p2, "k_3_fu_232_p2");
    sc_trace(mVcdFile, tmp_15_fu_246_p2, "tmp_15_fu_246_p2");
    sc_trace(mVcdFile, tmp_16_fu_251_p2, "tmp_16_fu_251_p2");
    sc_trace(mVcdFile, tmp_6_fu_284_p1, "tmp_6_fu_284_p1");
    sc_trace(mVcdFile, tmp_20_fu_288_p2, "tmp_20_fu_288_p2");
    sc_trace(mVcdFile, tmp_5_fu_300_p2, "tmp_5_fu_300_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

bigint_math_bigint_rightshift::~bigint_math_bigint_rightshift() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void bigint_math_bigint_rightshift::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_180_p2.read()))) {
        i_i_reg_88 = i_5_fu_186_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_i_reg_88 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_180_p2.read()))) {
        i_reg_99 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_218_p3.read()))) {
        i_reg_99 = i_3_reg_335.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        j_reg_122 = j_4_fu_318_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_197_p2.read(), ap_const_lv1_0))) {
        j_reg_122 = ap_const_lv4_7;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        k_1_reg_134 = k_2_phi_fu_161_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_197_p2.read(), ap_const_lv1_0))) {
        k_1_reg_134 = k_reg_110.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_180_p2.read()))) {
        k_reg_110 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_218_p3.read()))) {
        k_reg_110 = p_k_1_fu_238_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        outputBit_reg_145 = outputBit_2_fu_312_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_197_p2.read(), ap_const_lv1_0))) {
        outputBit_reg_145 = ap_const_lv32_6;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_fu_197_p2.read(), ap_const_lv1_0))) {
        a_addr_reg_340 =  (sc_lv<8>) (tmp_fu_209_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        b_reg_359 = b_fu_257_p2.read();
        tmp_17_reg_365 = tmp_17_fu_262_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_3_reg_335 = i_3_fu_203_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        j_cast_reg_345 = j_cast_fu_214_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_fu_262_p2.read()))) {
        k_4_reg_374 = k_4_fu_273_p2.read();
        out_addr_reg_379 =  (sc_lv<8>) (tmp_18_fu_279_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_fu_262_p2.read()))) {
        out_addr_1_reg_369 =  (sc_lv<8>) (tmp_21_fu_268_p1.read());
    }
}

void bigint_math_bigint_rightshift::thread_a_address0() {
    a_address0 = a_addr_reg_340.read();
}

void bigint_math_bigint_rightshift::thread_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          !esl_seteq<1,1,1>(exitcond_fu_197_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(exitcond_fu_197_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_sig_107() {
    ap_sig_107 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void bigint_math_bigint_rightshift::thread_ap_sig_23() {
    ap_sig_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void bigint_math_bigint_rightshift::thread_ap_sig_47() {
    ap_sig_47 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void bigint_math_bigint_rightshift::thread_ap_sig_56() {
    ap_sig_56 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void bigint_math_bigint_rightshift::thread_ap_sig_71() {
    ap_sig_71 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void bigint_math_bigint_rightshift::thread_ap_sig_86() {
    ap_sig_86 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void bigint_math_bigint_rightshift::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_23.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_47.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_56.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_71.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_86.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_107.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_b_fu_257_p2() {
    b_fu_257_p2 = (!j_cast_reg_345.read().is_01())? sc_lv<8>(): tmp_16_fu_251_p2.read() >> (unsigned short)j_cast_reg_345.read().to_uint();
}

void bigint_math_bigint_rightshift::thread_exitcond_fu_197_p2() {
    exitcond_fu_197_p2 = (!i_reg_99.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_99.read() == ap_const_lv9_100);
}

void bigint_math_bigint_rightshift::thread_exitcond_i_fu_180_p2() {
    exitcond_i_fu_180_p2 = (!i_i_reg_88.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_88.read() == ap_const_lv9_100);
}

void bigint_math_bigint_rightshift::thread_i_3_fu_203_p2() {
    i_3_fu_203_p2 = (!i_reg_99.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_99.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void bigint_math_bigint_rightshift::thread_i_5_fu_186_p2() {
    i_5_fu_186_p2 = (!i_i_reg_88.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_i_reg_88.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void bigint_math_bigint_rightshift::thread_j_4_fu_318_p2() {
    j_4_fu_318_p2 = (!j_reg_122.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_122.read()) + sc_bigint<4>(ap_const_lv4_F));
}

void bigint_math_bigint_rightshift::thread_j_cast_fu_214_p1() {
    j_cast_fu_214_p1 = esl_sext<8,4>(j_reg_122.read());
}

void bigint_math_bigint_rightshift::thread_k_2_phi_fu_161_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read())) {
            k_2_phi_fu_161_p4 = k_1_reg_134.read();
        } else if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read())) {
            k_2_phi_fu_161_p4 = k_4_reg_374.read();
        } else {
            k_2_phi_fu_161_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        k_2_phi_fu_161_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void bigint_math_bigint_rightshift::thread_k_3_fu_232_p2() {
    k_3_fu_232_p2 = (!k_1_reg_134.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(k_1_reg_134.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void bigint_math_bigint_rightshift::thread_k_4_fu_273_p2() {
    k_4_fu_273_p2 = (!ap_const_lv32_1.is_01() || !k_1_reg_134.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(k_1_reg_134.read()));
}

void bigint_math_bigint_rightshift::thread_out_r_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read()))) {
        out_r_address0 = out_addr_reg_379.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read()))) {
        out_r_address0 = out_addr_1_reg_369.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        out_r_address0 =  (sc_lv<8>) (tmp_i_fu_192_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_fu_262_p2.read()))) {
        out_r_address0 =  (sc_lv<8>) (tmp_18_fu_279_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_fu_262_p2.read()))) {
        out_r_address0 =  (sc_lv<8>) (tmp_21_fu_268_p1.read());
    } else {
        out_r_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void bigint_math_bigint_rightshift::thread_out_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_fu_262_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_fu_262_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read())))) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_out_r_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read()))) {
        out_r_d0 = tmp_19_fu_305_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read()))) {
        out_r_d0 = tmp_22_fu_293_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        out_r_d0 = ap_const_lv8_0;
    } else {
        out_r_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void bigint_math_bigint_rightshift::thread_out_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_180_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read())))) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void bigint_math_bigint_rightshift::thread_outputBit_1_phi_fu_172_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read())) {
            outputBit_1_phi_fu_172_p4 = outputBit_reg_145.read();
        } else if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_reg_365.read())) {
            outputBit_1_phi_fu_172_p4 = ap_const_lv32_7;
        } else {
            outputBit_1_phi_fu_172_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        outputBit_1_phi_fu_172_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void bigint_math_bigint_rightshift::thread_outputBit_2_fu_312_p2() {
    outputBit_2_fu_312_p2 = (!outputBit_1_phi_fu_172_p4.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(outputBit_1_phi_fu_172_p4.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void bigint_math_bigint_rightshift::thread_p_k_1_fu_238_p3() {
    p_k_1_fu_238_p3 = (!tmp_s_fu_226_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_s_fu_226_p2.read()[0].to_bool())? k_3_fu_232_p2.read(): k_1_reg_134.read());
}

void bigint_math_bigint_rightshift::thread_tmp_15_fu_246_p2() {
    tmp_15_fu_246_p2 = (!j_cast_reg_345.read().is_01())? sc_lv<8>(): ap_const_lv8_1 << (unsigned short)j_cast_reg_345.read().to_uint();
}

void bigint_math_bigint_rightshift::thread_tmp_16_fu_251_p2() {
    tmp_16_fu_251_p2 = (tmp_15_fu_246_p2.read() & a_q0.read());
}

void bigint_math_bigint_rightshift::thread_tmp_17_fu_262_p2() {
    tmp_17_fu_262_p2 = (!outputBit_reg_145.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<1>(): sc_lv<1>(outputBit_reg_145.read() == ap_const_lv32_FFFFFFFF);
}

void bigint_math_bigint_rightshift::thread_tmp_18_fu_279_p1() {
    tmp_18_fu_279_p1 = esl_sext<64,32>(k_4_fu_273_p2.read());
}

void bigint_math_bigint_rightshift::thread_tmp_19_fu_305_p2() {
    tmp_19_fu_305_p2 = (!out_r_q0.read().is_01() || !tmp_5_fu_300_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(out_r_q0.read()) + sc_biguint<8>(tmp_5_fu_300_p2.read()));
}

void bigint_math_bigint_rightshift::thread_tmp_20_fu_288_p2() {
    tmp_20_fu_288_p2 = (!tmp_6_fu_284_p1.read().is_01())? sc_lv<8>(): b_reg_359.read() << (unsigned short)tmp_6_fu_284_p1.read().to_uint();
}

void bigint_math_bigint_rightshift::thread_tmp_21_fu_268_p1() {
    tmp_21_fu_268_p1 = esl_sext<64,32>(k_1_reg_134.read());
}

void bigint_math_bigint_rightshift::thread_tmp_22_fu_293_p2() {
    tmp_22_fu_293_p2 = (!tmp_20_fu_288_p2.read().is_01() || !out_r_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_20_fu_288_p2.read()) + sc_biguint<8>(out_r_q0.read()));
}

void bigint_math_bigint_rightshift::thread_tmp_4_fu_218_p3() {
    tmp_4_fu_218_p3 = j_reg_122.read().range(3, 3);
}

void bigint_math_bigint_rightshift::thread_tmp_5_fu_300_p2() {
    tmp_5_fu_300_p2 = (!ap_const_lv8_7.is_01())? sc_lv<8>(): b_reg_359.read() << (unsigned short)ap_const_lv8_7.to_uint();
}

void bigint_math_bigint_rightshift::thread_tmp_6_fu_284_p1() {
    tmp_6_fu_284_p1 = outputBit_reg_145.read().range(8-1, 0);
}

void bigint_math_bigint_rightshift::thread_tmp_fu_209_p1() {
    tmp_fu_209_p1 = esl_zext<64,9>(i_reg_99.read());
}

void bigint_math_bigint_rightshift::thread_tmp_i_fu_192_p1() {
    tmp_i_fu_192_p1 = esl_zext<64,9>(i_i_reg_88.read());
}

void bigint_math_bigint_rightshift::thread_tmp_s_fu_226_p2() {
    tmp_s_fu_226_p2 = (!outputBit_reg_145.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(outputBit_reg_145.read() == ap_const_lv32_0);
}

void bigint_math_bigint_rightshift::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_180_p2.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(exitcond_fu_197_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_218_p3.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

