#pragma line 1 "BigInt/solution1/main.cpp" ::: -10
#pragma line 1 "BigInt/solution1/main.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 145 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 407 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 188
#pragma line 421 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 191
#pragma line 6 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "BigInt/solution1/main.cpp" 2 ::: 195
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 196
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 224
#pragma line 128 "/usr/include/features.h" 3 4 ::: 325
#pragma line 149 "/usr/include/features.h" 3 4 ::: 339
#pragma line 177 "/usr/include/features.h" 3 4 ::: 341
#pragma line 193 "/usr/include/features.h" 3 4 ::: 344
#pragma line 350 "/usr/include/features.h" 3 4 ::: 375
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 379
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 414
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 420
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 443
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 484
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 490
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 508
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 514
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 518
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 520
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 524
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 534
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 587
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 628
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 649
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 673
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 674
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 676
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 678
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 679
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 704
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 715
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 720
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 721
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 722
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 729
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 765
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 768
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 770
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 798
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 800
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 802
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 863
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 870
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 888
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 893
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 904
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 973
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 987
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 990
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 991
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1023
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1039
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1064
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1067
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1072
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1094
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1115
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1118
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1129
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1139
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1141
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1145
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1194
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1195
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1201
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1203
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1227
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1238
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1279
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1281
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1303
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1363
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1378
#pragma line 526 "/usr/include/libio.h" 3 4 ::: 1390
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1392
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1398
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1449
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1465
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1482
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1514
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1591
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1730
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1750
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2003
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2014
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2051
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2083
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2151
#pragma line 943 "/usr/include/stdio.h" 3 4 ::: 2154
#pragma line 2 "BigInt/solution1/main.cpp" 2 ::: 2156
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2157
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2190
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2215
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2218
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2228
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2257
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2275
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2276
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2332
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2333
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2370
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2372
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2376
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2379
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2397
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2398
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2400
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2402
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2410
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2428
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2431
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2434
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2436
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2437
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2471
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2477
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2482
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2484
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2625
#pragma line 39 "/usr/include/xlocale.h" ::: 2667
#pragma line 236 "/usr/include/stdlib.h" 2 3 4 ::: 2672
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2709
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2723
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2804
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2812
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2821
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2822
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2843
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2846
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2849
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2852
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2855
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2870
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2895
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2898
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2908
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2943
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2974
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2997
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2999
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3001
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3002
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3006
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3046
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3057
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3078
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3086
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3088
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3123
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3210
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3214
#pragma line 58 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3250
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3254
#pragma line 262 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3276
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3286
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3308
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3310
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3312
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3313
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3336
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3356
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3426
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3457
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3461
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3604
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3633
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3658
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3683
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3686
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3701
#pragma line 630 "/usr/include/stdlib.h" 3 4 ::: 3830
#pragma line 652 "/usr/include/stdlib.h" 3 4 ::: 3844
#pragma line 684 "/usr/include/stdlib.h" 3 4 ::: 3868
#pragma line 706 "/usr/include/stdlib.h" 3 4 ::: 3881
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4132
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 4150
#pragma line 968 "/usr/include/stdlib.h" 3 4 ::: 4153
#pragma line 3 "BigInt/solution1/main.cpp" 2 ::: 4155
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/ap_utils.h" 1 ::: 4156
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 4216
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4249
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4274
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 4277
#pragma line 96 "/usr/include/string.h" 3 4 ::: 4318
#pragma line 199 "/usr/include/string.h" 3 4 ::: 4413
#pragma line 212 "/usr/include/string.h" 3 4 ::: 4415
#pragma line 236 "/usr/include/string.h" 3 4 ::: 4417
#pragma line 263 "/usr/include/string.h" 3 4 ::: 4422
#pragma line 315 "/usr/include/string.h" 3 4 ::: 4452
#pragma line 342 "/usr/include/string.h" 3 4 ::: 4457
#pragma line 436 "/usr/include/string.h" 3 4 ::: 4539
#pragma line 489 "/usr/include/string.h" 3 4 ::: 4570
#pragma line 517 "/usr/include/string.h" 3 4 ::: 4576
#pragma line 644 "/usr/include/string.h" 3 4 ::: 4665
#pragma line 60 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/ap_utils.h" 2 ::: 4667
#pragma line 73 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/ap_utils.h" ::: 4668
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 4669
#pragma line 74 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/ap_utils.h" 2 ::: 4804
#pragma line 4 "BigInt/solution1/main.cpp" 2 ::: 4811
