#pragma line 1 "BigInt/solution1/main.cpp" ::: 0
#pragma line 1 "BigInt/solution1/main.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 145 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 407 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 198
#pragma line 421 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 201
#pragma line 6 "<command line>" 2 ::: 203
#pragma line 1 "<built-in>" 2 ::: 204
#pragma line 1 "BigInt/solution1/main.cpp" 2 ::: 205
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 206
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 234
#pragma line 128 "/usr/include/features.h" 3 4 ::: 335
#pragma line 149 "/usr/include/features.h" 3 4 ::: 349
#pragma line 177 "/usr/include/features.h" 3 4 ::: 351
#pragma line 193 "/usr/include/features.h" 3 4 ::: 354
#pragma line 350 "/usr/include/features.h" 3 4 ::: 385
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 389
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 424
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 430
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 453
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 494
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 500
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 518
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 524
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 528
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 530
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 534
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 544
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 597
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 638
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 659
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 683
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 684
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 686
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 688
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 689
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 714
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 725
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 730
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 731
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 732
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 739
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 775
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 778
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 780
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 808
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 810
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 812
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 873
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 880
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 898
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 903
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 914
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 983
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 997
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1000
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1001
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1033
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1049
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1074
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1077
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1082
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1104
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1125
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1128
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1139
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1149
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1151
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1155
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1204
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1205
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1211
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1213
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1237
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1248
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1289
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1291
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1313
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1373
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1388
#pragma line 526 "/usr/include/libio.h" 3 4 ::: 1400
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1402
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1408
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1459
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1475
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1492
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1524
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1601
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1740
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1760
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2013
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2024
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2061
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2093
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2161
#pragma line 943 "/usr/include/stdio.h" 3 4 ::: 2164
#pragma line 2 "BigInt/solution1/main.cpp" 2 ::: 2166
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2167
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2200
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2225
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2228
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2238
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2267
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2285
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2286
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2342
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2343
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2380
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2382
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2386
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2389
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2407
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2408
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2410
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2412
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2420
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2438
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2441
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2444
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2446
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2447
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2481
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2487
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2492
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2494
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2635
#pragma line 236 "/usr/include/stdlib.h" 2 3 4 ::: 2678
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2715
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2729
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2810
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2818
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2827
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2828
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2849
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2852
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2855
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2858
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2861
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2876
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2901
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2904
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2914
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2949
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2980
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3003
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3005
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3007
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3008
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3012
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3052
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3063
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3084
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3092
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3094
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3129
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3216
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3220
#pragma line 58 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3256
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3260
#pragma line 262 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3282
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3292
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3314
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3316
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3318
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3319
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3342
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3362
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3432
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3463
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3467
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3610
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3639
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3664
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3689
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3692
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3707
#pragma line 630 "/usr/include/stdlib.h" 3 4 ::: 3836
#pragma line 652 "/usr/include/stdlib.h" 3 4 ::: 3850
#pragma line 684 "/usr/include/stdlib.h" 3 4 ::: 3874
#pragma line 706 "/usr/include/stdlib.h" 3 4 ::: 3887
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4138
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 4156
#pragma line 968 "/usr/include/stdlib.h" 3 4 ::: 4159
#pragma line 3 "BigInt/solution1/main.cpp" 2 ::: 4161
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/ap_utils.h" 1 ::: 4162
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 4222
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4255
#pragma line 56 "/home/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4280
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 4283
#pragma line 96 "/usr/include/string.h" 3 4 ::: 4324
#pragma line 199 "/usr/include/string.h" 3 4 ::: 4419
#pragma line 212 "/usr/include/string.h" 3 4 ::: 4421
#pragma line 236 "/usr/include/string.h" 3 4 ::: 4423
#pragma line 263 "/usr/include/string.h" 3 4 ::: 4428
#pragma line 315 "/usr/include/string.h" 3 4 ::: 4458
#pragma line 342 "/usr/include/string.h" 3 4 ::: 4463
#pragma line 436 "/usr/include/string.h" 3 4 ::: 4545
#pragma line 489 "/usr/include/string.h" 3 4 ::: 4576
#pragma line 517 "/usr/include/string.h" 3 4 ::: 4582
#pragma line 644 "/usr/include/string.h" 3 4 ::: 4671
#pragma line 60 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/ap_utils.h" 2 ::: 4673
#pragma line 73 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/ap_utils.h" ::: 4674
#pragma line 1 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 4675
#pragma line 74 "/home/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/ap_utils.h" 2 ::: 4810
#pragma line 4 "BigInt/solution1/main.cpp" 2 ::: 4817
